clear
close all
clc
recycle('off');

%% CODEGEN SCRIPT for SR-UKF/SR-USKF modules
% 27-04-2026    Pietro Califano     Compile and validate SR_UKF observation, UD wrapper, time update,
%                                   and full-step orchestration entrypoints.

charScriptDir = fileparts(mfilename('fullpath'));
charRepoRoot = fullfile(charScriptDir, '..', '..');
addpath(charRepoRoot, '-begin');
addpath(genpath(fullfile(charRepoRoot, 'matlab')), '-begin');
addpath(genpath(fullfile(charRepoRoot, 'lib', 'SimulationGears_for_SpaceNav', 'matlab')), '-begin');
addpath(genpath(fullfile(charRepoRoot, 'lib', 'SimulationGears_for_SpaceNav', ...
                        'lib', 'MathCore_for_SpaceNav', 'matlab')), '-begin');

[dxState, ...
 dStateSqrtCov, ...
 dStateTimetag, ...
 dTargetTimetag, ...
 dxSigmaPoints, ...
 dUprior, ...
 dDprior, ...
 strMeasBus, ...
 strDynParams, ...
 strMeasModelParams, ...
 strFilterMutabConfig, ...
 strFilterConstConfig] = BuildDefaultInputs_();

cfg = coder.config('mex');
cfg.GenerateReport = false;
cfg.RowMajor = false;

constFilterConfig = coder.Constant(strFilterConstConfig);

codegen('-config', cfg, ...
        'SR_UKF_ObsUp', ...
        '-args', {dxState, dStateSqrtCov, dStateTimetag, dxSigmaPoints, strMeasBus, ...
                  strDynParams, strMeasModelParams, strFilterMutabConfig, constFilterConfig}, ...
        '-o', 'SR_UKF_ObsUp_MEX');

codegen('-config', cfg, ...
        'SR_UKF_UDCov_ObsUp', ...
        '-args', {dxState, dUprior, dDprior, dStateTimetag, dxSigmaPoints, strMeasBus, ...
                  strDynParams, strMeasModelParams, strFilterMutabConfig, constFilterConfig}, ...
        '-o', 'SR_UKF_UDCov_ObsUp_MEX');

codegen('-config', cfg, ...
        'SR_UKF_TimeUp', ...
        '-args', {dxState, dStateSqrtCov, dStateTimetag, dTargetTimetag, ...
                  strDynParams, strFilterMutabConfig, constFilterConfig}, ...
        '-o', 'SR_UKF_TimeUp_MEX');

codegen('-config', cfg, ...
        'SR_UKF_step', ...
        '-args', {dxState, dStateSqrtCov, dStateTimetag, dTargetTimetag, strMeasBus, ...
                  strMeasModelParams, strDynParams, strFilterMutabConfig, constFilterConfig}, ...
        '-o', 'SR_UKF_step_MEX');

ValidateEquivalence_(dxState, ...
                     dStateSqrtCov, ...
                     dStateTimetag, ...
                     dTargetTimetag, ...
                     dxSigmaPoints, ...
                     dUprior, ...
                     dDprior, ...
                     strMeasBus, ...
                     strDynParams, ...
                     strMeasModelParams, ...
                     strFilterMutabConfig, ...
                     strFilterConstConfig);

function [dxState, ...
          dStateSqrtCov, ...
          dStateTimetag, ...
          dTargetTimetag, ...
          dxSigmaPoints, ...
          dUprior, ...
          dDprior, ...
          strMeasBus, ...
          strDynParams, ...
          strMeasModelParams, ...
          strFilterMutabConfig, ...
          strFilterConstConfig] = BuildDefaultInputs_()

strFilterConstConfig = filter_tailoring.BuildArchitectureTemplate(bWriteBusDefs=false, ...
                                                                  ui16StateSize=uint16(17));
                                                                  
strFilterConstConfig.ui16NumWindowPoses = uint16(0);
strFilterConstConfig.ui16WindowPoseSize = uint16(0);
strFilterConstConfig.ui16WindowStateCovSize = uint16(0);
strFilterConstConfig.ui32WindowMaxSize = uint32(0);
strFilterConstConfig.ui32FullStateSize = uint32(strFilterConstConfig.ui16StateSize);
strFilterConstConfig.ui32FullCovSize = uint32(strFilterConstConfig.ui16StateSize);
strFilterConstConfig.ui16MaxResidualsVecSize = uint16(6);
strFilterConstConfig.ui8MeasVecSize = uint8(6);
strFilterConstConfig.enumMeasDelayManagementMode = EnumMeasDelayManagementMode.NONE;
strFilterConstConfig.enumSigmaPointResidualMode = EnumSigmaPointResidualMode.ADDITIVE;

[strFilterMutabConfig, strDynParams, strMeasModelParams, strMeasBus] = ...
    filter_tailoring.BuildInputStructsTemplate(strFilterConstConfig);

ui16StateSize = strFilterConstConfig.ui16StateSize;
ui8MeasVecSize = strFilterConstConfig.ui8MeasVecSize;

dxState = linspace(0.1, 1.7, double(ui16StateSize)).';
dStateCov = diag(linspace(0.2, 0.8, double(ui16StateSize)));
dStateSqrtCov = chol(dStateCov, 'upper');
dStateTimetag = 0.0;
dTargetTimetag = 0.0;

strFilterMutabConfig.dSqrtRmeasNoiseCov = chol(0.1 * eye(double(ui8MeasVecSize)), 'upper');
strFilterMutabConfig.bNewMeasAvailable = true;
strFilterMutabConfig.bEnableAdaptivity = true;
strFilterMutabConfig.bAdaptMeasNoiseCov = true;
strFilterMutabConfig.bAdaptProcessNoiseCov = true;
strFilterMutabConfig.dIntegrTimestep = 1.0;

strMeasBus.dyMeasVec = dxState(1:double(ui8MeasVecSize)) + 0.05 .* (1:double(ui8MeasVecSize)).';
strMeasBus.bValidMeasBool = true(double(ui8MeasVecSize), 1);
strMeasBus.bMeasTypeFlags(:) = false;
strMeasBus.bMeasTypeFlags(1) = true;
strMeasBus.dMeasTimetags(:) = 0.0;

dxSigmaPoints = CDensityFcnPropagator.GenerateSigmaPointsSet(dxState, ...
                                                             dStateSqrtCov, ...
                                                             strFilterMutabConfig.ui32UnscentedNumSigmaPoints, ...
                                                             strFilterMutabConfig.dPerturbScale);
[dUprior, dDprior] = UDdecomposition(dStateCov);
end

function ValidateEquivalence_(dxState, ...
                              dStateSqrtCov, ...
                              dStateTimetag, ...
                              dTargetTimetag, ...
                              dxSigmaPoints, ...
                              dUprior, ...
                              dDprior, ...
                              strMeasBus, ...
                              strDynParams, ...
                              strMeasModelParams, ...
                              strFilterMutabConfig, ...
                              strFilterConstConfig)
dTol = 1.0e-10;

[dxObsRef, dSqrtObsRef, dTimeObsRef, strMutObsRef, dResObsRef, dKObsRef, dxErrObsRef, dSyyObsRef] = ...
    SR_UKF_ObsUp(dxState, dStateSqrtCov, dStateTimetag, dxSigmaPoints, strMeasBus, ...
                 strDynParams, strMeasModelParams, strFilterMutabConfig, strFilterConstConfig);
[dxObsMex, dSqrtObsMex, dTimeObsMex, strMutObsMex, dResObsMex, dKObsMex, dxErrObsMex, dSyyObsMex] = ...
    SR_UKF_ObsUp_MEX(dxState, dStateSqrtCov, dStateTimetag, dxSigmaPoints, strMeasBus, ...
                     strDynParams, strMeasModelParams, strFilterMutabConfig, strFilterConstConfig);

AssertNear_(dxObsMex, dxObsRef, dTol);
AssertNear_(dSqrtObsMex, dSqrtObsRef, dTol);
AssertNear_(dTimeObsMex, dTimeObsRef, dTol);
AssertNear_(strMutObsMex.dSqrtRmeasNoiseCov, strMutObsRef.dSqrtRmeasNoiseCov, dTol);
AssertNear_(strMutObsMex.dSqrtQprocessNoiseCov, strMutObsRef.dSqrtQprocessNoiseCov, dTol);
AssertNear_(dResObsMex, dResObsRef, dTol);
AssertNear_(dKObsMex, dKObsRef, dTol);
AssertNear_(dxErrObsMex, dxErrObsRef, dTol);
AssertNear_(dSyyObsMex, dSyyObsRef, dTol);

[dxUdRef, dUref, dDref, ~, ~, dResUdRef, dKUdRef, dxErrUdRef, dPyyUdRef] = ...
    SR_UKF_UDCov_ObsUp(dxState, dUprior, dDprior, dStateTimetag, dxSigmaPoints, strMeasBus, ...
                       strDynParams, strMeasModelParams, strFilterMutabConfig, strFilterConstConfig);
[dxUdMex, dUmex, dDmex, ~, ~, dResUdMex, dKUdMex, dxErrUdMex, dPyyUdMex] = ...
    SR_UKF_UDCov_ObsUp_MEX(dxState, dUprior, dDprior, dStateTimetag, dxSigmaPoints, strMeasBus, ...
                           strDynParams, strMeasModelParams, strFilterMutabConfig, strFilterConstConfig);

AssertNear_(dxUdMex, dxUdRef, dTol);
AssertNear_(dUmex, dUref, dTol);
AssertNear_(dDmex, dDref, dTol);
AssertNear_(dResUdMex, dResUdRef, dTol);
AssertNear_(dKUdMex, dKUdRef, dTol);
AssertNear_(dxErrUdMex, dxErrUdRef, dTol);
AssertNear_(dPyyUdMex, dPyyUdRef, dTol);

[dxTimeRef, dSqrtTimeRef, dTimeRef, ~, dSigmaRef, ~, ~, ~, ~, dQref] = ...
    SR_UKF_TimeUp(dxState, dStateSqrtCov, dStateTimetag, dTargetTimetag, ...
                  strDynParams, strFilterMutabConfig, strFilterConstConfig);
[dxTimeMex, dSqrtTimeMex, dTimeMex, ~, dSigmaMex, ~, ~, ~, ~, dQmex] = ...
    SR_UKF_TimeUp_MEX(dxState, dStateSqrtCov, dStateTimetag, dTargetTimetag, ...
                      strDynParams, strFilterMutabConfig, strFilterConstConfig);

AssertNear_(dxTimeMex, dxTimeRef, dTol);
AssertNear_(dSqrtTimeMex, dSqrtTimeRef, dTol);
AssertNear_(dTimeMex, dTimeRef, dTol);
AssertNear_(dSigmaMex, dSigmaRef, dTol);
AssertNear_(dQmex, dQref, dTol);

[strOutRef, dxStepRef, dSqrtStepRef, dTimeStepRef] = ...
    SR_UKF_step(dxState, dStateSqrtCov, dStateTimetag, dTargetTimetag, strMeasBus, ...
                strMeasModelParams, strDynParams, strFilterMutabConfig, strFilterConstConfig);
[strOutMex, dxStepMex, dSqrtStepMex, dTimeStepMex] = ...
    SR_UKF_step_MEX(dxState, dStateSqrtCov, dStateTimetag, dTargetTimetag, strMeasBus, ...
                    strMeasModelParams, strDynParams, strFilterMutabConfig, strFilterConstConfig);

AssertNear_(dxStepMex, dxStepRef, dTol);
AssertNear_(dSqrtStepMex, dSqrtStepRef, dTol);
AssertNear_(dTimeStepMex, dTimeStepRef, dTol);
AssertNear_(strOutMex.dKalmanGain, strOutRef.dKalmanGain, dTol);
AssertNear_(strOutMex.dxErrState, strOutRef.dxErrState, dTol);
AssertNear_(strOutMex.dSqrtSyyResCov, strOutRef.dSqrtSyyResCov, dTol);
AssertNear_(strOutMex.dxSigmaPointsPrior, strOutRef.dxSigmaPointsPrior, dTol);
end

function AssertNear_(dActual, dExpected, dTol)
assert(max(abs(dActual - dExpected), [], 'all') <= dTol);
end
