function [dxStatePost, ...
          dUpost, ...
          dDpost, ...
          dStateTimetag, ...
          strFilterMutabConfig, ...
          dAllPriorResVector, ...
          dKalmanGain, ...
          dxErrState, ...
          dPyyResCov] = SR_UKF_UDCov_ObsUp(dxState, ...
                                           dUprior, ...
                                           dDprior, ...
                                           dStateTimetag, ...
                                           dxSigmaPoints, ...
                                           strMeasBus, ...
                                           strDynParams, ...
                                           strMeasModelParams, ...
                                           strFilterMutabConfig, ...
                                           strFilterConstConfig) %#codegen
arguments
    dxState                 (:,1) double {mustBeReal}
    dUprior                 (:,:) double {mustBeReal}
    dDprior                 (:,:) double {mustBeReal}
    dStateTimetag           (:,1) double {mustBeReal}
    dxSigmaPoints           (:,:) double {mustBeReal}
    strMeasBus              (1,1) struct
    strDynParams            (1,1) struct
    strMeasModelParams      (1,1) struct
    strFilterMutabConfig    (1,1) struct
    strFilterConstConfig    (1,1) struct {coder.mustBeConst}
end
%% SIGNATURE
% [dxStatePost, ...
%  dUpost, ...
%  dDpost, ...
%  dStateTimetag, ...
%  strFilterMutabConfig, ...
%  dAllPriorResVector, ...
%  dKalmanGain, ...
%  dxErrState, ...
%  dPyyResCov] = SR_UKF_UDCov_ObsUp(dxState, ...
%                                   dUprior, ...
%                                   dDprior, ...
%                                   dStateTimetag, ...
%                                   dxSigmaPoints, ...
%                                   strMeasBus, ...
%                                   strDynParams, ...
%                                   strMeasModelParams, ...
%                                   strFilterMutabConfig, ...
%                                   strFilterConstConfig) %#codegen
% -------------------------------------------------------------------------------------------------------------
%% DESCRIPTION
% Modern UD-covariance observation update for the sigma-point runtime. The current implementation
% shares the same measurement-model, residual, and editing path as SR_UKF_ObsUp and only differs in
% the covariance representation exposed at the interface.
%
% The prior U/D factors are converted to an upper-triangular square-root covariance, the shared
% SR-UKF observation update is executed, and the posterior covariance is then mapped back to U/D
% form. This keeps the UD path interoperable with the other modernized templates while avoiding a
% second divergent observation-update implementation.
%
% TODO: Replace this transitional wrapper with a native UD sigma-point update rather than interface-level UD compatibility.
% -------------------------------------------------------------------------------------------------------------
%% CHANGELOG
% 24-04-2026    Pietro Califano     Replace the legacy stub with a modern UD wrapper aligned with
%                                   SR_UKF_ObsUp and the common tailoring interface.
% 27-04-2026    Pietro Califano     Rename to SR_UKF_UDCov_ObsUp and document the transitional UD contract.
% -------------------------------------------------------------------------------------------------------------

%% Function code

% Interface-level UD support: convert the prior to covariance form, run the shared SR-UKF update,
% then decompose the posterior back to U/D factors.
dStateCovPrior = RegularizeCovariance_(dUprior * dDprior * dUprior');
[dSqrtStateCovPrior, i32Flag] = FactorizeCovariance(dStateCovPrior);

if coder.target('MATLAB') || coder.target('MEX')
    assert(i32Flag == 0, ...
        'ERROR: SR_UKF_UDCov_ObsUp failed to factorize the prior UD covariance.');
end

% Run the shared SR-UKF observation update with the square-root covariance representation
[dxStatePost, ...
 dSqrtStateCovPost, ...
 dStateTimetag, ...
 strFilterMutabConfig, ...
 dAllPriorResVector, ...
 dKalmanGain, ...
 dxErrState, ...
 dSqrtSyyResCov] = SR_UKF_ObsUp(dxState, ...
                                dSqrtStateCovPrior, ...
                                dStateTimetag, ...
                                dxSigmaPoints, ...
                                strMeasBus, ...
                                strDynParams, ...
                                strMeasModelParams, ...
                                strFilterMutabConfig, ...
                                strFilterConstConfig);

% Re-build the posterior covariance from the updated square-root factor and decompose back to UD form for output
dStateCovPost = dSqrtStateCovPost' * dSqrtStateCovPost;

% TODO recompose UD factors directly from the updated square-root covariance without explicitly forming the dense covariance in between.
[dUpost, dDpost] = UDdecomposition(RegularizeCovariance_(dStateCovPost));
dPyyResCov = dSqrtSyyResCov' * dSqrtSyyResCov;

end

%% Internal helper functions
function dCovariance = RegularizeCovariance_(dCovariance)
dCovariance = 0.5 .* (dCovariance + dCovariance');

if coder.target('MATLAB') || coder.target('MEX')
    dMinDiag = min(diag(dCovariance));
    if dMinDiag <= 0.0
        dCovariance = dCovariance + (abs(dMinDiag) + 1.0e-12) .* eye(size(dCovariance));
    end
end
end
