function [strFilterOutputData, dxState, dxStateSqrtCov, dStateTimetag, ...
          strDynParams, strFilterMutabConfig, strMeasModelParams] = SR_UKF_step(dxState, ...
                                                                               dxStateSqrtCov, ...
                                                                               dStateTimetag, ...
                                                                               dTargetTimetag, ...
                                                                               strMeasBus, ...
                                                                               strMeasModelParams, ...
                                                                               strDynParams, ...
                                                                               strFilterMutabConfig, ...
                                                                               strFilterConstConfig) %#codegen
arguments
    dxState                 (:,1) double {mustBeReal}
    dxStateSqrtCov          (:,:) double {mustBeReal}
    dStateTimetag           (:,1) double {mustBeReal}
    dTargetTimetag          (1,1) double {mustBeReal}
    strMeasBus              (1,1) struct
    strMeasModelParams      (1,1) struct
    strDynParams            (1,1) struct
    strFilterMutabConfig    (1,1) struct
    strFilterConstConfig    (1,1) struct {coder.mustBeConst}
end
%% SIGNATURE
% [strFilterOutputData, dxState, dxStateSqrtCov, dStateTimetag, ...
%  strDynParams, strFilterMutabConfig, strMeasModelParams] = SR_UKF_step(dxState, ...
%                                                                        dxStateSqrtCov, ...
%                                                                        dStateTimetag, ...
%                                                                        dTargetTimetag, ...
%                                                                        strMeasBus, ...
%                                                                        strMeasModelParams, ...
%                                                                        strDynParams, ...
%                                                                        strFilterMutabConfig, ...
%                                                                        strFilterConstConfig) %#codegen
% -------------------------------------------------------------------------------------------------------------
%% DESCRIPTION
% One-step SR-UKF/SR-USKF orchestration with the same argument order and output-bus style as
% EKF_SlideWindow_step. It performs time update, optional observation update, and exposes the
% residual/gain/square-root innovation statistics required by external adaptivity modules.
%
% The orchestrator does not include built-in adaptivity and does not implement EKF delayed-measurement
% backward propagation. Those policies must remain external to the SR-UKF estimator kernel until their
% square-root/sigma-point contracts are defined.
% -------------------------------------------------------------------------------------------------------------
%% CHANGELOG
% 27-04-2026    Pietro Califano     Add SR-UKF full-step orchestration with EKF-style interface and
%                                   externalized adaptivity statistics.
% -------------------------------------------------------------------------------------------------------------

%% Function code
strFilterConstConfig = coder.const(strFilterConstConfig);

% Input checks (MATLAB/MEX only)
if coder.const(strFilterConstConfig.enumMeasDelayManagementMode ~= EnumMeasDelayManagementMode.NONE)
    error('SR_UKF_step:UnsupportedLatency', ...
          'SR_UKF_step does not implement EKF delayed-measurement backward propagation.');
end

bFiringManoeuvre = false;
if coder.const(isfield(strDynParams, "bFiringManoeuvre"))
    bFiringManoeuvre = strDynParams.bFiringManoeuvre;
end

ui16StateSize = coder.const(strFilterConstConfig.ui16StateSize);
ui8MeasVecSize = coder.const(strFilterConstConfig.ui8MeasVecSize);
ui16MaxResidualsVecSize = coder.const(strFilterConstConfig.ui16MaxResidualsVecSize);

if uint16(ui8MeasVecSize) > ui16MaxResidualsVecSize
    error('SR_UKF_step:InvalidResidualAllocation', ...
          'ui16MaxResidualsVecSize must cover ui8MeasVecSize for the SR-UKF output bus.');
end

% Allocate the EKF-compatible output bus before branching so all step paths expose the same fields.
strFilterOutputData = struct();
coder.cstructname(strFilterOutputData, "SR_UKF_output_data");

strFilterOutputData.dKalmanGain = zeros(double(ui16StateSize), double(ui16MaxResidualsVecSize));
strFilterOutputData.dxErrState = zeros(double(ui16StateSize), 1);
strFilterOutputData.dPyyResCov = zeros(double(ui16MaxResidualsVecSize), double(ui16MaxResidualsVecSize));
strFilterOutputData.dSqrtSyyResCov = zeros(double(ui16MaxResidualsVecSize), double(ui16MaxResidualsVecSize));
strFilterOutputData.dAllPriorResVector = zeros(double(ui16MaxResidualsVecSize), 1);
strFilterOutputData.dAllObservJac = zeros(double(ui16MaxResidualsVecSize), double(ui16StateSize));
strFilterOutputData.dMeasUpdateTimetag = 0.0;
strFilterOutputData.dxStatePrior = zeros(double(ui16StateSize), 1);
strFilterOutputData.dxStateSqrtCovPrior = zeros(double(ui16StateSize), double(ui16StateSize));
strFilterOutputData.dxSigmaPointsPrior = zeros(double(ui16StateSize), double(2 * ui16StateSize + 1));
strFilterOutputData.dFlowSTM = eye(double(ui16StateSize));
strFilterOutputData.dDynMatrix = zeros(double(ui16StateSize));
strFilterOutputData.dDynMatrixNext = zeros(double(ui16StateSize));
strFilterOutputData.dIntegrProcessNoiseCovQ = zeros(double(ui16StateSize));

% Execute time update
[dxStatePrior, ...
 dxStateSqrtCovPrior, ...
 dStateTimetag, ...
 strDynParams, ...
 dxSigmaPointsPrior, ...
 dFlowSTM, ...
 dDynMatrix, ...
 dDynMatrixNext, ...
 strFilterMutabConfig, ...
 dIntegrProcessNoiseCovQ] = SR_UKF_TimeUp(dxState, ...
                                          dxStateSqrtCov, ...
                                          dStateTimetag, ...
                                          dTargetTimetag, ...
                                          strDynParams, ...
                                          strFilterMutabConfig, ...
                                          strFilterConstConfig);

dxState(:) = dxStatePrior;
dxStateSqrtCov(:,:) = dxStateSqrtCovPrior;
strMeasModelParams.dFlowSTM = dFlowSTM;
strMeasModelParams.dIntegrProcessNoiseCovQ = dIntegrProcessNoiseCovQ;

% Execute measurement update if measurements are available and not in a firing manoeuvre
if strFilterMutabConfig.bNewMeasAvailable && ~bFiringManoeuvre
    [dxStatePost, ...
     dxStateSqrtCovPost, ...
     dStateTimetag, ...
     strFilterMutabConfig, ...
     dAllPriorResVector, ...
     dKalmanGain, ...
     dxErrState, ...
     dSqrtSyyResCov] = SR_UKF_ObsUp(dxStatePrior, ...
                                    dxStateSqrtCovPrior, ...
                                    dStateTimetag, ...
                                    dxSigmaPointsPrior, ...
                                    strMeasBus, ...
                                    strDynParams, ...
                                    strMeasModelParams, ...
                                    strFilterMutabConfig, ...
                                    strFilterConstConfig);

    dxState(:) = dxStatePost;
    dxStateSqrtCov(:,:) = dxStateSqrtCovPost;

    % Assign output data from measurement update
    strFilterOutputData.dKalmanGain(:, 1:double(ui8MeasVecSize)) = dKalmanGain;
    strFilterOutputData.dxErrState(:) = dxErrState;
    strFilterOutputData.dAllPriorResVector(1:double(ui8MeasVecSize)) = dAllPriorResVector;
    strFilterOutputData.dSqrtSyyResCov(1:double(ui8MeasVecSize), 1:double(ui8MeasVecSize)) = dSqrtSyyResCov;
    strFilterOutputData.dPyyResCov(1:double(ui8MeasVecSize), 1:double(ui8MeasVecSize)) = dSqrtSyyResCov' * dSqrtSyyResCov;
    strFilterOutputData.dMeasUpdateTimetag = dStateTimetag(1);
end

% Pack output data
strFilterOutputData.dxStatePrior = dxStatePrior;
strFilterOutputData.dxStateSqrtCovPrior = dxStateSqrtCovPrior;
strFilterOutputData.dxSigmaPointsPrior = dxSigmaPointsPrior;
strFilterOutputData.dFlowSTM = dFlowSTM;
strFilterOutputData.dDynMatrix = dDynMatrix;
strFilterOutputData.dDynMatrixNext = dDynMatrixNext;
strFilterOutputData.dIntegrProcessNoiseCovQ = dIntegrProcessNoiseCovQ;

end
