function [dxStatePost, ...
          dUpost, ...
          dDpost, ...
          dStateTimetag, ...
          strFilterMutabConfig, ...
          dAllPriorResVector, ...
          dKalmanGain, ...
          dxErrState, ...
          dPyyResCov] = SRUSKF_UDcov_ObsUpDT(dxState, ...
                                             dUprior, ...
                                             dDprior, ...
                                             dStateTimetag, ...
                                             dxSigmaPoints, ...
                                             strMeasBus, ...
                                             strDynParams, ...
                                             strMeasModelParams, ...
                                             strFilterMutabConfig, ...
                                             strFilterConstConfig) %#codegen
arguments
    dxState                 (:,1) double {mustBeReal}
    dUprior                 (:,:) double {mustBeReal}
    dDprior                 (:,:) double {mustBeReal}
    dStateTimetag           (1,1) double {mustBeReal}
    dxSigmaPoints           (:,:) double {mustBeReal}
    strMeasBus              (1,1) struct
    strDynParams            (1,1) struct
    strMeasModelParams      (1,1) struct
    strFilterMutabConfig    (1,1) struct
    strFilterConstConfig    (1,1) struct
end
%% SIGNATURE
% [dxStatePost, ...
%  dUpost, ...
%  dDpost, ...
%  dStateTimetag, ...
%  strFilterMutabConfig, ...
%  dAllPriorResVector, ...
%  dKalmanGain, ...
%  dxErrState, ...
%  dPyyResCov] = SRUSKF_UDcov_ObsUpDT(dxState, ...
%                                     dUprior, ...
%                                     dDprior, ...
%                                     dStateTimetag, ...
%                                     dxSigmaPoints, ...
%                                     strMeasBus, ...
%                                     strDynParams, ...
%                                     strMeasModelParams, ...
%                                     strFilterMutabConfig, ...
%                                     strFilterConstConfig) %#codegen
% -------------------------------------------------------------------------------------------------------------
%% DESCRIPTION
% Modern UD-covariance observation update for the sigma-point runtime. The current implementation
% shares the exact same measurement-model, residual, editing, and adaptivity path as
% SR_UKF_Adaptive_ObsUp and only differs in the covariance representation exposed at the interface.
%
% The prior U/D factors are converted to an upper-triangular square-root covariance, the shared
% SR-UKF observation update is executed, and the posterior covariance is then mapped back to U/D
% form. This keeps the UD path interoperable with the other modernized templates while avoiding a
% second divergent observation-update implementation.
% -------------------------------------------------------------------------------------------------------------
%% CHANGELOG
% 24-04-2026    Pietro Califano     Replace the legacy stub with a modern UD wrapper aligned with
%                                   SR_UKF_Adaptive_ObsUp and the common tailoring interface.
% -------------------------------------------------------------------------------------------------------------

dStateCovPrior = ComposeUDcovariance_(dUprior, dDprior);
dSqrtStateCovPrior = FactorizeCovariance_(dStateCovPrior);

[dxStatePost, ...
 dSqrtStateCovPost, ...
 dStateTimetag, ...
 strFilterMutabConfig, ...
 dAllPriorResVector, ...
 dKalmanGain, ...
 dxErrState, ...
 dSqrtSyyResCov] = SR_UKF_Adaptive_ObsUp(dxState, ...
                                         dSqrtStateCovPrior, ...
                                         dStateTimetag, ...
                                         dxSigmaPoints, ...
                                         strMeasBus, ...
                                         strDynParams, ...
                                         strMeasModelParams, ...
                                         strFilterMutabConfig, ...
                                         strFilterConstConfig);

dStateCovPost = dSqrtStateCovPost' * dSqrtStateCovPost;
[dUpost, dDpost] = UDdecomposition(RegularizeCovariance_(dStateCovPost));
dPyyResCov = dSqrtSyyResCov' * dSqrtSyyResCov;

end

function dCovariance = ComposeUDcovariance_(dUfactor, dDfactor)
dCovariance = dUfactor * dDfactor * dUfactor';
dCovariance = RegularizeCovariance_(dCovariance);
end

function dCovariance = RegularizeCovariance_(dCovariance)
dCovariance = 0.5 .* (dCovariance + dCovariance');

if coder.target('MATLAB') || coder.target('MEX')
    dMinDiag = min(diag(dCovariance));
    if dMinDiag <= 0.0
        dCovariance = dCovariance + (abs(dMinDiag) + 1.0e-12) .* eye(size(dCovariance));
    end
end
end

function dSqrtCov = FactorizeCovariance_(dCovariance)
dCovariance = RegularizeCovariance_(dCovariance);
[dSqrtCov, i32Flag] = chol(dCovariance, 'upper');

if i32Flag ~= 0
    dJitterScale = max(1.0, max(abs(diag(dCovariance))));
    [dSqrtCov, i32Flag] = chol(dCovariance + 1.0e-12 .* dJitterScale .* eye(size(dCovariance)), 'upper');
end

if coder.target('MATLAB') || coder.target('MEX')
    assert(i32Flag == 0, ...
        'ERROR: SRUSKF_UDcov_ObsUpDT failed to factorize the prior UD covariance.');
end
end
