function tests = testComputeJosephConsiderUpdate
%% SIGNATURE
% tests = testComputeJosephConsiderUpdate
% -------------------------------------------------------------------------------------------------------------
%% DESCRIPTION
% Validate standard, underweighted, rejected, and Schmidt-consider Joseph
% measurement updates against independent dense-matrix references.
% -------------------------------------------------------------------------------------------------------------
%% INPUT
% None.
% -------------------------------------------------------------------------------------------------------------
%% OUTPUT
% tests    Function-based MATLAB test suite.
% -------------------------------------------------------------------------------------------------------------
%% CHANGELOG
% 05-08-2026  Pietro Califano, Codex gpt-5.6     First implementation.
% 06-08-2026  Pietro Califano, Codex gpt-5.6     Align reference names with Joseph update algebra.
% -------------------------------------------------------------------------------------------------------------
%% DEPENDENCIES
% ComputeJosephConsiderUpdate.
% -------------------------------------------------------------------------------------------------------------

% MATLAB function-based test entrypoints cannot use argument-validation
% blocks; functiontests validates this framework contract during discovery.
tests = functiontests(localfunctions);
end

function setupOnce(testCase)
charThisDir = fileparts(mfilename('fullpath'));
charRepoRoot = fullfile(charThisDir, '..', '..', '..');

testCase.TestData.charOriginalPath = path;
addpath(charRepoRoot);
SetupPaths_EstimationGears;
end

function teardownOnce(testCase)
path(testCase.TestData.charOriginalPath);
end

function testStandardJosephUpdateMatchesIndependentReference(testCase)
[dStateCovPrior, dMeasurementResidual, dMeasurementCov, dStateObservationMatrix] = ...
    BuildUpdateFixture_();

[dxErrorState, dStateCovPost, bUpdateAccepted, ...
 dSquaredMahalanobisDistance] = ...
    ComputeJosephConsiderUpdate(dStateCovPrior, dMeasurementResidual, ...
                                dMeasurementCov, dStateObservationMatrix, 0.0, ...
                                false(8, 1), false, 10.0);
[dxExpectedErrorState, dExpectedStateCovPost, dExpectedMahalanobisDistanceSq] = ...
    ComputeJosephReference_(dStateCovPrior, dMeasurementResidual, dMeasurementCov, ...
                            dStateObservationMatrix, 0.0, false(8, 1));

verifyTrue(testCase, bUpdateAccepted);
verifyEqual(testCase, dxErrorState, dxExpectedErrorState, 'AbsTol', 4.0e-13);
verifyEqual(testCase, dStateCovPost, dExpectedStateCovPost, 'AbsTol', 5.0e-13);
verifyEqual(testCase, dSquaredMahalanobisDistance, ...
            dExpectedMahalanobisDistanceSq, 'AbsTol', 2.0e-14);
end

function testUnderweightedJosephUpdateUsesOneEffectiveNoiseCovariance(testCase)
[dStateCovPrior, dMeasurementResidual, dMeasurementCov, dStateObservationMatrix] = ...
    BuildUpdateFixture_();
dMeasurementUnderweightCoeff = 0.025;

[dxErrorState, dStateCovPost, bUpdateAccepted, ...
 dSquaredMahalanobisDistance] = ...
    ComputeJosephConsiderUpdate(dStateCovPrior, dMeasurementResidual, ...
                                dMeasurementCov, dStateObservationMatrix, ...
                                dMeasurementUnderweightCoeff, false(8, 1), ...
                                false, 10.0);
[dxExpectedErrorState, dExpectedStateCovPost, dExpectedMahalanobisDistanceSq] = ...
    ComputeJosephReference_(dStateCovPrior, dMeasurementResidual, dMeasurementCov, ...
                            dStateObservationMatrix, ...
                            dMeasurementUnderweightCoeff, false(8, 1));

verifyTrue(testCase, bUpdateAccepted);
verifyEqual(testCase, dxErrorState, dxExpectedErrorState, 'AbsTol', 4.0e-13);
verifyEqual(testCase, dStateCovPost, dExpectedStateCovPost, 'AbsTol', 5.0e-13);
verifyEqual(testCase, dSquaredMahalanobisDistance, ...
            dExpectedMahalanobisDistanceSq, 'AbsTol', 2.0e-14);
end

function testWholeMeasurementRejectionReturnsPriorUnchanged(testCase)
[dStateCovPrior, dMeasurementResidual, dMeasurementCov, dStateObservationMatrix] = ...
    BuildUpdateFixture_();
dMeasurementResidual = 40.0 .* dMeasurementResidual;

[dxErrorState, dStateCovPost, bUpdateAccepted, ...
 dSquaredMahalanobisDistance] = ...
    ComputeJosephConsiderUpdate(dStateCovPrior, dMeasurementResidual, ...
                                dMeasurementCov, dStateObservationMatrix, 0.025, ...
                                false(8, 1), true, 1.0);

verifyFalse(testCase, bUpdateAccepted);
verifyGreaterThanOrEqual(testCase, dSquaredMahalanobisDistance, 1.0);
verifyEqual(testCase, dxErrorState, zeros(8, 1), 'AbsTol', 0.0);
verifyEqual(testCase, dStateCovPost, dStateCovPrior, 'AbsTol', 0.0);
end

function testDisabledRejectionStillAppliesLargeInnovation(testCase)
[dStateCovPrior, dMeasurementResidual, dMeasurementCov, dStateObservationMatrix] = ...
    BuildUpdateFixture_();
dMeasurementResidual = 40.0 .* dMeasurementResidual;

[dxErrorState, ~, bUpdateAccepted, dSquaredMahalanobisDistance] = ...
    ComputeJosephConsiderUpdate(dStateCovPrior, dMeasurementResidual, ...
                                dMeasurementCov, dStateObservationMatrix, 0.0, ...
                                false(8, 1), false, 1.0);

verifyTrue(testCase, bUpdateAccepted);
verifyGreaterThanOrEqual(testCase, dSquaredMahalanobisDistance, 1.0);
verifyGreaterThan(testCase, norm(dxErrorState), 1.0);
end

function testSchmidtGainMaskFreezesConsiderMeanAndAutocovariance(testCase)
[dStateCovPrior, dMeasurementResidual, dMeasurementCov, dStateObservationMatrix] = ...
    BuildUpdateFixture_();
bConsiderStateMask = false(8, 1);
bConsiderStateMask([2, 7]) = true;

[dxErrorState, dStateCovPost, bUpdateAccepted] = ...
    ComputeJosephConsiderUpdate(dStateCovPrior, dMeasurementResidual, ...
                                dMeasurementCov, dStateObservationMatrix, 0.025, ...
                                bConsiderStateMask, false, 10.0);
[dxExpectedErrorState, dExpectedStateCovPost] = ComputeJosephReference_( ...
    dStateCovPrior, dMeasurementResidual, dMeasurementCov, dStateObservationMatrix, ...
    0.025, bConsiderStateMask);

verifyTrue(testCase, bUpdateAccepted);
verifyEqual(testCase, dxErrorState, dxExpectedErrorState, 'AbsTol', 4.0e-13);
verifyEqual(testCase, dStateCovPost, dExpectedStateCovPost, 'AbsTol', 5.0e-13);
verifyEqual(testCase, dxErrorState(bConsiderStateMask), zeros(2, 1), ...
            'AbsTol', 0.0);
verifyEqual(testCase, ...
    dStateCovPost(bConsiderStateMask, bConsiderStateMask), ...
    dStateCovPrior(bConsiderStateMask, bConsiderStateMask), 'AbsTol', 4.0e-13);
verifyGreaterThan(testCase, norm( ...
    dStateCovPost(~bConsiderStateMask, bConsiderStateMask) - ...
    dStateCovPrior(~bConsiderStateMask, bConsiderStateMask), 'fro'), ...
    1.0e-12);
verifyEqual(testCase, chol(dStateCovPost, 'lower') * ...
            transpose(chol(dStateCovPost, 'lower')), dStateCovPost, ...
            'AbsTol', 6.0e-13);
end

function testRejectsInvalidCovarianceAndMeasurementInputs(testCase)
[dStateCovPrior, dMeasurementResidual, dMeasurementCov, dStateObservationMatrix] = ...
    BuildUpdateFixture_();
dNonSymmetricPriorCov = dStateCovPrior;
dNonSymmetricPriorCov(1, 2) = dNonSymmetricPriorCov(1, 2) + 0.2;
dIndefinitePriorCov = eye(8);
dIndefinitePriorCov(1:2, 1:2) = [1.0, 2.0; 2.0, 1.0];
dIndefiniteMeasurementCov = eye(3);
dIndefiniteMeasurementCov(1:2, 1:2) = [1.0, 2.0; 2.0, 1.0];

verifyError(testCase, @() ComputeJosephConsiderUpdate( ...
    dNonSymmetricPriorCov, dMeasurementResidual, dMeasurementCov, ...
    dStateObservationMatrix, ...
    0.0, false(8, 1), false, 10.0), ...
    'ComputeJosephConsiderUpdate:InvalidPriorCovariance');
verifyError(testCase, @() ComputeJosephConsiderUpdate( ...
    dIndefinitePriorCov, dMeasurementResidual, dMeasurementCov, ...
    dStateObservationMatrix, ...
    0.0, false(8, 1), false, 10.0), ...
    'ComputeJosephConsiderUpdate:PriorCovarianceNotPositiveDefinite');
verifyError(testCase, @() ComputeJosephConsiderUpdate( ...
    dStateCovPrior, [NaN; dMeasurementResidual(2:3)], dMeasurementCov, ...
    dStateObservationMatrix, 0.0, false(8, 1), false, 10.0), ...
    'ComputeJosephConsiderUpdate:InvalidMeasurement');
verifyError(testCase, @() ComputeJosephConsiderUpdate( ...
    dStateCovPrior, dMeasurementResidual, dIndefiniteMeasurementCov, ...
    dStateObservationMatrix, 0.0, false(8, 1), false, 10.0), ...
    'ComputeJosephConsiderUpdate:MeasurementCovarianceNotPositiveDefinite');
verifyError(testCase, @() ComputeJosephConsiderUpdate( ...
    dStateCovPrior, dMeasurementResidual, dMeasurementCov, dStateObservationMatrix, ...
    -0.1, false(8, 1), false, 10.0), ...
    'ComputeJosephConsiderUpdate:InvalidUpdatePolicy');
end

function [dStateCovPrior, dMeasurementResidual, dMeasurementCov, ...
          dStateObservationMatrix] = ...
        BuildUpdateFixture_()
% Build a deterministic dense positive-definite prior and a coupled observation
% model so consider-state and cross-covariance behavior are observable.
dStateCovRoot = diag(linspace(1.0, 1.7, 8));
dStateCovRoot(2:end, 1) = [0.1; -0.05; 0.08; 0.03; -0.04; 0.06; 0.02];
dStateCovRoot(4:end, 3) = [0.07; -0.02; 0.05; 0.04; -0.03];
dStateCovPrior = dStateCovRoot * transpose(dStateCovRoot);
dMeasurementResidual = [0.8; -0.4; 0.3];
dMeasurementCov = [0.4, 0.03, -0.01; ...
                   0.03, 0.5, 0.02; ...
                   -0.01, 0.02, 0.6];
dStateObservationMatrix = ...
    [1.0, 0.0, 0.2, 0.0, 0.0, -0.1, 0.0, 0.0; ...
     0.0, 1.0, 0.0, 0.0, 0.3, 0.0, 0.0, -0.2; ...
     0.0, 0.0, 0.0, 1.0, 0.0, 0.15, -0.25, 0.0];
end

function [dxErrorState, dStateCovPost, ...
          dSquaredMahalanobisDistance] = ...
        ComputeJosephReference_(dStateCovPrior, dMeasurementResidual, ...
                                dMeasurementCov, dStateObservationMatrix, ...
                                dMeasurementUnderweightCoeff, ...
                                bConsiderStateMask)
% Form the dense reference directly with matrix division so it remains
% implementation-independent from the production Cholesky solve.
dPredictedMeasurementCov = dStateObservationMatrix * dStateCovPrior * ...
    transpose(dStateObservationMatrix);
dEffectiveMeasurementCov = dMeasurementCov + ...
    dMeasurementUnderweightCoeff .* dPredictedMeasurementCov;
dInnovationCov = dPredictedMeasurementCov + dEffectiveMeasurementCov;
dKalmanGain = dStateCovPrior * transpose(dStateObservationMatrix) / ...
    dInnovationCov;
dKalmanGain(bConsiderStateMask, :) = 0.0;

% Apply the same Schmidt policy to both reference equations; this checks the
% production routine's gain masking and Joseph propagation as one contract.
dxErrorState = dKalmanGain * dMeasurementResidual;
dJosephStateTransform = eye(size(dStateCovPrior)) - ...
    dKalmanGain * dStateObservationMatrix;
dStateCovPost = dJosephStateTransform * dStateCovPrior * ...
    transpose(dJosephStateTransform) + dKalmanGain * ...
    dEffectiveMeasurementCov * transpose(dKalmanGain);
dStateCovPost = 0.5 .* (dStateCovPost + transpose(dStateCovPost));
dSquaredMahalanobisDistance = ...
    transpose(dMeasurementResidual) / dInnovationCov * dMeasurementResidual;
end
