classdef testGivensRotUpdate < matlab.unittest.TestCase
    methods (TestClassSetup)
        function addProjectPaths(~)
            charThisDir = fileparts(mfilename('fullpath'));
            addpath(fullfile(charThisDir, '..', '..', '..'));
            SetupPaths_EstimationGears;
        end
    end

    methods (Test)
        function testTapleyExampleMatchesFixtureAndCovariance(testCase)
            [dxPrior, dPcov, dYmeasVec, dHobsMatrix, dMeasCovSR] = BuildTapleyProblem_();
            dSRInfoMatPrior = chol(inv(dPcov));

            [dxPost, dSRInfoMatPost, dInfoVecPost, dErrorVec, dSqrtPxPost, dJcost] = ComputeGivensRotMeasUpdate_SRIF(dxPrior, ...
                dSRInfoMatPrior, ...
                dYmeasVec, ...
                dHobsMatrix, ...
                false, ...
                false, ...
                dMeasCovSR);

            dxExpected = [1.00335913215659; 0.970062794753707];
            dPxExpected = inv(inv(dPcov) + dHobsMatrix' * dHobsMatrix);

            testCase.verifyEqual(dxPost, dxExpected, 'AbsTol', 1e-9);
            testCase.verifyEqual(dInfoVecPost, dSRInfoMatPost * dxPost, 'AbsTol', 1e-12);
            testCase.verifyEqual(dSqrtPxPost * dSqrtPxPost', dPxExpected, 'AbsTol', 1e-10);
            testCase.verifyEqual(dJcost, sum(dErrorVec .* dErrorVec), 'AbsTol', 1e-12);
        end

        function testWhiteningAndLowerPriorFactorMatchWeightedLeastSquares(testCase)
            dxPrior = [0.5; -0.2];
            dPcov = [3.0, 0.4; 0.4, 2.0];
            dYmeasVec = [1.2; -0.7; 0.3];
            dHobsMatrix = [1.0, 2.0; -1.0, 0.5; 0.5, -0.25];
            dMeasCov = [2.0, 0.3, 0.0; 0.3, 1.5, 0.2; 0.0, 0.2, 1.0];
            dMeasCovSR = chol(dMeasCov, 'lower');
            dSRInfoMatPrior = chol(dPcov, 'lower') \ eye(2);

            [dxPost, dSRInfoMatPost, dInfoVecPost, ~, dSqrtPxPost] = ComputeGivensRotMeasUpdate_SRIF(dxPrior, ...
                dSRInfoMatPrior, ...
                dYmeasVec, ...
                dHobsMatrix, ...
                false, ...
                true, ...
                dMeasCovSR);

            dInfoMatExpected = inv(dPcov) + dHobsMatrix' * (dMeasCov \ dHobsMatrix);
            dPxExpected = inv(dInfoMatExpected);
            dxExpected = dPxExpected * (inv(dPcov) * dxPrior + dHobsMatrix' * (dMeasCov \ dYmeasVec));

            testCase.verifyEqual(dxPost, dxExpected, 'AbsTol', 1e-10);
            testCase.verifyEqual(dInfoVecPost, dSRInfoMatPost * dxPost, 'AbsTol', 1e-12);
            testCase.verifyEqual(dSqrtPxPost * dSqrtPxPost', dPxExpected, 'AbsTol', 1e-10);
        end

        function testNoPriorWhitenedMatchesWeightedLeastSquares(testCase)
            dxPrior = zeros(2, 1);
            dYmeasVec = [1.0; 2.0; 0.5];
            dHobsMatrix = [1.0, 0.0; 0.0, 1.0; 1.0, 1.0];
            dMeasCov = [1.0, 0.2, 0.0; 0.2, 2.0, 0.1; 0.0, 0.1, 1.5];
            dMeasCovSR = chol(dMeasCov, 'lower');

            [dxPost, dSRInfoMatPost, dInfoVecPost] = ComputeGivensRotMeasUpdate_SRIF(dxPrior, ...
                eye(2), ...
                dYmeasVec, ...
                dHobsMatrix, ...
                true, ...
                true, ...
                dMeasCovSR);

            dInfoMatExpected = dHobsMatrix' * (dMeasCov \ dHobsMatrix);
            dxExpected = dInfoMatExpected \ (dHobsMatrix' * (dMeasCov \ dYmeasVec));

            testCase.verifyEqual(dxPost, dxExpected, 'AbsTol', 1e-10);
            testCase.verifyEqual(dInfoVecPost, dSRInfoMatPost * dxPost, 'AbsTol', 1e-12);
        end

        function testExplicitEKFGivensWrappersMatchDirectSRIFUpdate(testCase)
            dxPrior = [0.5; -0.2];
            dPcov = [3.0, 0.4; 0.4, 2.0];
            dYmeasVec = [1.2; -0.7; 0.3];
            dHobsMatrix = [1.0, 2.0; -1.0, 0.5; 0.5, -0.25];
            dMeasCovSR = eye(3);
            dSRInfoMatPrior = chol(inv(dPcov));

            [dxSrif, dSRInfoMatPost, ~, ~, dSqrtPxPost] = ComputeGivensRotMeasUpdate_SRIF(dxPrior, ...
                dSRInfoMatPrior, ...
                dYmeasVec, ...
                dHobsMatrix, ...
                false, ...
                false, ...
                dMeasCovSR);

            dPxExpected = dSqrtPxPost * dSqrtPxPost';

            [dxFullCov, dPxFullCov] = ComputeGivensRotMeasUpdate_FullCovEKF(dxPrior, ...
                dPcov, ...
                dYmeasVec, ...
                dHobsMatrix, ...
                false, ...
                false, ...
                dMeasCovSR);

            [dUPrior, dDPrior] = UDdecomposition(dPcov);
            [dxUDCov, dUPost, dDPost] = ComputeGivensRotMeasUpdate_UDCovEKF(dxPrior, ...
                dUPrior, ...
                dDPrior, ...
                dYmeasVec, ...
                dHobsMatrix, ...
                false, ...
                false, ...
                dMeasCovSR);

            [dxSqrtCov, dSqrtPxPostWrapper] = ComputeGivensRotMeasUpdate_SqrtCovEKF(dxPrior, ...
                chol(dPcov, 'lower'), ...
                dYmeasVec, ...
                dHobsMatrix, ...
                false, ...
                false, ...
                dMeasCovSR);

            testCase.verifyEqual(dxFullCov, dxSrif, 'AbsTol', 1e-10);
            testCase.verifyEqual(dxUDCov, dxSrif, 'AbsTol', 1e-10);
            testCase.verifyEqual(dxSqrtCov, dxSrif, 'AbsTol', 1e-10);
            testCase.verifyEqual(dPxFullCov, dPxExpected, 'AbsTol', 1e-10);
            testCase.verifyEqual(dUPost * dDPost * dUPost', dPxExpected, 'AbsTol', 1e-10);
            testCase.verifyEqual(dSqrtPxPostWrapper' * dSqrtPxPostWrapper, dPxExpected, 'AbsTol', 1e-10);
        end

        function testSqrtCovWrapperAcceptsUpperAndLowerFactors(testCase)
            dxPrior = [0.5; -0.2];
            dPcov = [3.0, 0.4; 0.4, 2.0];
            dYmeasVec = [1.2; -0.7; 0.3];
            dHobsMatrix = [1.0, 2.0; -1.0, 0.5; 0.5, -0.25];
            dMeasCovSR = eye(3);

            [dxPostLower, dSqrtPostLowerInput] = ComputeGivensRotMeasUpdate_SqrtCovEKF(dxPrior, ...
                chol(dPcov, 'lower'), ...
                dYmeasVec, ...
                dHobsMatrix, ...
                false, ...
                false, ...
                dMeasCovSR);

            [dxPostUpper, dSqrtPostUpperInput] = ComputeGivensRotMeasUpdate_SqrtCovEKF(dxPrior, ...
                chol(dPcov, 'upper'), ...
                dYmeasVec, ...
                dHobsMatrix, ...
                false, ...
                false, ...
                dMeasCovSR);

            testCase.verifyEqual(dxPostUpper, dxPostLower, 'AbsTol', 1e-10);
            testCase.verifyEqual(dSqrtPostUpperInput, dSqrtPostLowerInput, 'AbsTol', 1e-10);
            testCase.verifyTrue(istriu(dSqrtPostUpperInput));
        end

        function testModifiedAgeeTurnerMatchesGivensRotUDCovWrapper(testCase)
            [dxPrior, dPcov, dYmeasVec, dHobsMatrix, dMeasCovSR] = BuildTapleyProblem_();
            [dUprior, dDxPrior] = UDdecomposition(dPcov);

            [dxPost, dPxPost, dDxPost] = ComputeGivensRotMeasUpdate_UDCovEKF(dxPrior, ...
                dUprior, ...
                dDxPrior, ...
                dYmeasVec, ...
                dHobsMatrix, ...
                false, ...
                false, ...
                dMeasCovSR);

            dyRes = dYmeasVec - dHobsMatrix * dxPrior;
            [dzPost, dUpost, ~, dDpost, dxErrState] = UDobsUpdate_ModAgeeTurner(dxPrior, ...
                dUprior, ...
                dDxPrior, ...
                chol(dMeasCovSR), ...
                dHobsMatrix, ...
                dyRes, ...
                false);

            testCase.verifyEqual(dzPost, dxPost, 'AbsTol', 1e-10);
            testCase.verifyEqual(dxErrState, dxPost - dxPrior, 'AbsTol', 1e-10);
            testCase.verifyEqual(dPxPost * dDxPost * dPxPost', dUpost * dDpost * dUpost', 'AbsTol', 1e-10);
        end

    end
end

function [dxPrior, dPcov, dYmeasVec, dHobsMatrix, dMeasCovSR] = BuildTapleyProblem_()
dxPrior = [2; 2];
dPcov = diag([100, 100]);
dYmeasVec = [-1.1; 1.2; 1.8];
dHobsMatrix = [1, -2; ...
               2, -1; ...
               1, 1];
dMeasCovSR = eye(3);
end
