clear
close all
clc
recycle('off');

%% CODEGEN SCRIPT for ComputeGivensRotMeasUpdate_SRIF() function
% 25-04-2024    Pietro Califano     First codegen script.
% 24-04-2026    Pietro Califano     Replaced the missing makeCodegen helper with a direct MATLAB
%                                   Coder invocation.
% 27-04-2026    Pietro Califano     Rename target and add generated-MEX equivalence validation.
% 27-04-2026    Pietro Califano     Rename the generated-MEX fixture RHS away from measurement-vector
%                                   terminology. The low-level SRIF contract must not imply absolute
%                                   Euclidean measurements.

charScriptDir = fileparts(mfilename('fullpath'));
charRepoRoot = fullfile(charScriptDir, '..', '..');
addpath(charRepoRoot, '-begin');
addpath(genpath(fullfile(charRepoRoot, 'matlab')), '-begin');
addpath(genpath(fullfile(charRepoRoot, 'lib', 'SimulationGears_for_SpaceNav', ...
                        'lib', 'MathCore_for_SpaceNav', 'matlab')), '-begin');

targetFcnName = 'ComputeGivensRotMeasUpdate_SRIF';
targetMexName = 'ComputeGivensRotMeasUpdate_SRIF_MEX';

nMaxStates = 100;
nMaxMeas = 100;
nStateSize = 2;
nMeasSize = 3;

dxPrior         = coder.typeof(0, [nMaxStates, 1], [1,0]);
dSRInfoMatPrior = coder.typeof(0, [nMaxStates, nMaxStates], [1,1]);
dLinearizedObsRhs = coder.typeof(0, [nMaxMeas, 1], [1,0]);
dHobsMatrix     = coder.typeof(0, [nMaxMeas, nMaxStates], [1,1]);
bNoPriorInfo    = coder.typeof(false, [1,1]);
bRunPrewhiten  = coder.typeof(false, [1,1]);
dMeasCovSR      = coder.typeof(0, [nMaxMeas, nMaxMeas], [1,1]);
ui32StateSize   = coder.Constant(uint32(nStateSize));
ui32MeasSize    = coder.Constant(uint32(nMeasSize));
ui32MaxStateSize = coder.Constant(uint32(nMaxStates));
ui32MaxMeasSize = coder.Constant(uint32(nMaxMeas));

args_cell = {dxPrior, ...
             dSRInfoMatPrior, ...
             dLinearizedObsRhs, ...
             dHobsMatrix, ...
             bNoPriorInfo, ...
             bRunPrewhiten, ...
             dMeasCovSR, ...
             ui32StateSize, ...
             ui32MeasSize, ...
             ui32MaxStateSize, ...
             ui32MaxMeasSize};

cfg = coder.config('mex');
cfg.GenerateReport = false;
cfg.RowMajor = false;

codegen('-config', cfg, targetFcnName, '-args', args_cell, '-o', targetMexName);

%% Run equivalence test
[dxPriorTest, dSRInfoMatPriorTest, dLinearizedObsRhsTest, dHobsMatrixTest, dMeasCovSRTest] = BuildEquivalenceProblem_();
[dxPostRef, dSRInfoMatPostRef, dInfoVecPostRef, dErrorVecRef, dSqrtPxPostRef, dJcostRef] = ...
    ComputeGivensRotMeasUpdate_SRIF(dxPriorTest, ...
                                    dSRInfoMatPriorTest, ...
                                    dLinearizedObsRhsTest, ...
                                    dHobsMatrixTest, ...
                                    false, ...
                                    false, ...
                                    dMeasCovSRTest, ...
                                    uint32(nStateSize), ...
                                    uint32(nMeasSize), ...
                                    uint32(nMaxStates), ...
                                    uint32(nMaxMeas));

[dxPostMex, dSRInfoMatPostMex, dInfoVecPostMex, dErrorVecMex, dSqrtPxPostMex, dJcostMex] = ...
    ComputeGivensRotMeasUpdate_SRIF_MEX(dxPriorTest, ...
                                        dSRInfoMatPriorTest, ...
                                        dLinearizedObsRhsTest, ...
                                        dHobsMatrixTest, ...
                                        false, ...
                                        false, ...
                                        dMeasCovSRTest, ...
                                        uint32(nStateSize), ...
                                        uint32(nMeasSize), ...
                                        uint32(nMaxStates), ...
                                        uint32(nMaxMeas));

dTol = 1.0e-12;
assert(max(abs(dxPostMex - dxPostRef), [], 'all') <= dTol);
assert(max(abs(dSRInfoMatPostMex - dSRInfoMatPostRef), [], 'all') <= dTol);
assert(max(abs(dInfoVecPostMex - dInfoVecPostRef), [], 'all') <= dTol);
assert(max(abs(dErrorVecMex - dErrorVecRef), [], 'all') <= dTol);
assert(max(abs(dSqrtPxPostMex - dSqrtPxPostRef), [], 'all') <= dTol);
assert(abs(dJcostMex - dJcostRef) <= dTol);

%% Local function
function [dxPrior, dSRInfoMatPrior, dLinearizedObsRhs, dHobsMatrix, dMeasCovSR] = BuildEquivalenceProblem_()
dxPrior = [2; 2];
dPcov = diag([100, 100]);
dSRInfoMatPrior = chol(inv(dPcov));
dLinearizedObsRhs = [-1.1; 1.2; 1.8];
dHobsMatrix = [1, -2; ...
               2, -1; ...
               1, 1];
dMeasCovSR = eye(3);
end
