classdef testPositionObservationModels < matlab.unittest.TestCase
    methods (TestClassSetup)
        function addProjectPaths(~)
            SetupPaths_EstimationGears;
        end
    end

    methods (Test)
        function testAbsolutePositionModelRunsDirectly(testCase)
            dxStateAtMeas = [3.0; 4.0; 12.0; 0.0; 0.0; 0.0; 0.1; -0.2; 0.3];

            [dExpectedMeas, dCamPosition_TF] = PredictAbsPosInTargetFrame(dxStateAtMeas(1:3), ...
                                                                          eye(3), ...
                                                                          10.0, ...
                                                                          zeros(3,1), ...
                                                                          dxStateAtMeas(7:9), ...
                                                                          uint8(1));
            [dPosObsMatrix, dBiasObsMatrix] = evalJAC_AbsPosInTargetFrame(dCamPosition_TF, ...
                                                                          eye(3), ...
                                                                          true, ...
                                                                          uint8(1));

            testCase.verifyEqual(dExpectedMeas, ComputeGeocentricLatLongAltitude(dxStateAtMeas(1:3)) + ...
                                               [-0.0; 0.0; -10.0] + dxStateAtMeas(7:9), 'AbsTol', 1e-12);
            testCase.verifySize(dPosObsMatrix, [3, 3]);
            testCase.verifySize(dBiasObsMatrix, [3, 3]);
        end

        function testRelativePositionModelRunsDirectly(testCase)
            dxStateAtMeas = [1.0; 2.0; 3.0; 0.0; 0.0; 0.0; 0.4; 0.5; 0.6];
            dDCM_CamFromSCB = [0.0, 0.0, -1.0; ...
                               0.0, 1.0,  0.0; ...
                               1.0, 0.0,  0.0];
            dDCM_SCBfromW = [0.0, -1.0, 0.0; ...
                             1.0,  0.0, 0.0; ...
                             0.0,  0.0, 1.0];

            dExpectedMeas = PredictCamToTargetPosition(dxStateAtMeas(1:3), ...
                                                       dDCM_CamFromSCB, ...
                                                       dDCM_SCBfromW, ...
                                                       [7.0; 8.0; 9.0], ...
                                                       dxStateAtMeas(7:9));
            [dPosObsMatrix, dBiasObsMatrix] = evalJAC_RelVisNavPosition(dDCM_CamFromSCB, ...
                                                                        dDCM_SCBfromW, ...
                                                                        true);

            testCase.verifyEqual(dExpectedMeas, [-5.6; 6.5; -5.4], 'AbsTol', 1e-12);
            testCase.verifySize(dPosObsMatrix, [3, 3]);
            testCase.verifySize(dBiasObsMatrix, [3, 3]);
        end

        function testTemplateHookUsesObservedStateSelection(testCase)
            dxStateAtMeas = [1.0; 2.0; 3.0];
            bValidMeasBool = logical([true; false]);

            strFilterConfig = struct();
            strFilterConfig.ui8MeasVecSize = uint8(2);
            strFilterConfig.ui16StateSize = uint16(3);
            strFilterConfig.strStatesIdx.ui8ActiveStateIdx = uint8([1; 3]);

            strMeasModelParams = struct();

            [dyMeasPred, bValidPrediction, dHobsMatrix] = ...
                filter_tailoring.ComputeMeasPredAndObsJacobian(dxStateAtMeas, ...
                                                               bValidMeasBool, ...
                                                               strMeasModelParams, ...
                                                               strFilterConfig);

            testCase.verifyEqual(dyMeasPred, [1.0; 3.0], 'AbsTol', 1e-12);
            testCase.verifyEqual(bValidPrediction, bValidMeasBool);
            testCase.verifyEqual(dHobsMatrix, [1.0, 0.0, 0.0; 0.0, 0.0, 1.0], 'AbsTol', 1e-12);
        end

    end
end
