function RunEstimationGearsWrapperRegression(charCaseName, charToolboxPath, charMexPath)
%% SIGNATURE
% RunEstimationGearsWrapperRegression(charCaseName, charToolboxPath, charMexPath)
% -------------------------------------------------------------------------------------------------------------
%% DESCRIPTION
% MATLAB wrapper regression entry point for CTest.
% -------------------------------------------------------------------------------------------------------------
%% INPUT
% charCaseName   Test case name.
% charToolboxPath  Generated MATLAB class path.
% charMexPath    Generated MEX path.
% -------------------------------------------------------------------------------------------------------------
%% OUTPUT
% None.
% -------------------------------------------------------------------------------------------------------------
%% CHANGELOG
% 21-08-2026  Pietro Califano     First prototype.
% -------------------------------------------------------------------------------------------------------------
%% DEPENDENCIES
% estimation_gears.CWrapperPlaceholder generated by gtwrap.
% -------------------------------------------------------------------------------------------------------------

arguments
    charCaseName (1, :) char
    charToolboxPath (1, :) char
    charMexPath (1, :) char
end

addpath(charToolboxPath);
addpath(charMexPath);

switch charCaseName
    case 'load_construct_clear'
        objWrapper = estimation_gears.CWrapperPlaceholder();
        clear objWrapper;
        clear classes;
        clear mex;

    case 'live_exit'
        objWrapper = estimation_gears.CWrapperPlaceholder();
        assignin('base', 'objWrapperLive', objWrapper);

    case 'string_value'
        objWrapper = estimation_gears.CWrapperPlaceholder();
        objWrapper.setTextDataByValue('value_ok');
        assert(strcmp(objWrapper.getTextData(), 'value_ok'));
        clear objWrapper;
        clear classes;
        clear mex;

    case 'string_const_ref'
        objWrapper = estimation_gears.CWrapperPlaceholder();
        objWrapper.setTextDataByConstRef('const_ref_ok');
        assert(strcmp(objWrapper.getTextData(), 'const_ref_ok'));
        clear objWrapper;
        clear classes;
        clear mex;

    case 'uint32_roundtrip'
        objWrapper = estimation_gears.CWrapperPlaceholder();
        ui32FrameId = objWrapper.echoFrameId(uint32(7));
        assert(isa(ui32FrameId, 'uint32'));
        assert(ui32FrameId == uint32(7));
        clear objWrapper;
        clear classes;
        clear mex;

    case 'bad_input_recovery'
        objWrapper = estimation_gears.CWrapperPlaceholder();
        ui32EchoWrapperId = GetWrapperMethodId_(charToolboxPath, 'echoFrameId');
        try
            EstimationGears_for_SpaceNav_wrapper(ui32EchoWrapperId, objWrapper, 'bad');
            error('RunEstimationGearsWrapperRegression:ExpectedError', 'Bad direct MEX call unexpectedly passed.');
        catch objException
            if strcmp(objException.identifier, 'RunEstimationGearsWrapperRegression:ExpectedError')
                rethrow(objException);
            end
        end
        ui32FrameId = objWrapper.echoFrameId(uint32(9));
        assert(ui32FrameId == uint32(9));
        clear objWrapper;
        clear classes;
        clear mex;

    case 'stdout_error_recovery'
        objWrapper = estimation_gears.CWrapperPlaceholder();
        objWrapper.printToStdout();
        ui32StringWrapperId = GetWrapperMethodId_(charToolboxPath, 'setTextDataByConstRef');
        try
            EstimationGears_for_SpaceNav_wrapper(ui32StringWrapperId, objWrapper);
            error('RunEstimationGearsWrapperRegression:ExpectedError', 'Bad string MEX call unexpectedly passed.');
        catch objException
            if strcmp(objException.identifier, 'RunEstimationGearsWrapperRegression:ExpectedError')
                rethrow(objException);
            end
        end
        objWrapper.printToStdout();
        clear objWrapper;
        clear classes;
        clear mex;

    case 'clear_all'
        evalin('base', 'objWrapper = estimation_gears.CWrapperPlaceholder(); clear all;');

    otherwise
        error('RunEstimationGearsWrapperRegression:UnknownCase', 'Unknown MATLAB wrapper regression case: %s', charCaseName);
end

end

function ui32WrapperId = GetWrapperMethodId_(charToolboxPath, charMethodName)
arguments
    charToolboxPath (1, :) char
    charMethodName (1, :) char
end

charClassFile = fullfile(charToolboxPath, '+estimation_gears', 'CWrapperPlaceholder.m');
charClassText = fileread(charClassFile);
charPattern = [charMethodName, '[\s\S]*?EstimationGears_for_SpaceNav_wrapper\((\d+), this'];
cellTokens = regexp(charClassText, charPattern, 'tokens', 'once');
if isempty(cellTokens)
    error('RunEstimationGearsWrapperRegression:MissingWrapperId', ...
          'Could not find wrapper id for method %s.', charMethodName);
end
ui32WrapperId = uint32(str2double(cellTokens{1}));
end
