close all
clear
clc

% TEST SETUP
% load();


%% test_TimeUpdateStep
[dxStatePrior, ...
 dxStateCovPrior, ...
 dStateTimetag,...
 dflowSTM,...
 dDynMatrix,...
 dDynMatrixNext] = EKF_SlideWindow_FullCov_TimeUp(dxState, ...
                                                dxStateCov, ...
                                                dStateTimetag, ...
                                                dTargetTimetag, ...
                                                strDynParams, ...
                                                strFilterMutabConfig, ...
                                                strFilterConstConfig); 



