function [strFilterMutabConfig] = ComputeInputNoise(strFilterMutabConfig, ...
                                                    strDynParams, ...
                                                    strFilterConstConfig) %#codegen
arguments
    strFilterMutabConfig    (1,1) struct
    strDynParams            (1,1) struct
    strFilterConstConfig    (1,1) struct {coder.mustBeConst}
end
%% SIGNATURE
% [strFilterMutabConfig] = ComputeInputNoise(strFilterMutabConfig, ...
%                                            strDynParams, ...
%                                            strFilterConstConfig) %#codegen
% -------------------------------------------------------------------------------------------------------------
%% DESCRIPTION
% Assemble the shared-runtime mapped process-noise configuration expected by the EKF time update.
% The helper fills both:
%   1) dProcessNoiseMapMatrix
%   2) dInputProcessNoiseMatrix
%
% The allocation order is deterministic and follows the standard runtime blocks:
% velocity, attitude-bias random walk, FOGM states, and optional gravity-parameter random walk.
% -------------------------------------------------------------------------------------------------------------
%% CHANGELOG
% 23-04-2026    Pietro Califano     Add shared runtime helper for mapped process-noise assembly.
% -------------------------------------------------------------------------------------------------------------

ui16StateSize = strFilterConstConfig.ui16StateSize;
ui8NumInputNoiseChannels = GetFieldOrDefault_(strFilterConstConfig, "ui8NumOfInputNoiseChannels", uint8(0));

strFilterMutabConfig.dProcessNoiseMapMatrix = zeros(double(ui16StateSize), double(ui8NumInputNoiseChannels));
strFilterMutabConfig.dInputProcessNoiseMatrix = zeros(double(ui8NumInputNoiseChannels), double(ui8NumInputNoiseChannels));

if ui8NumInputNoiseChannels == 0 || ~isfield(strFilterConstConfig, "strStatesIdx")
    return
end

ui32NoiseAllocPtr = uint32(1);
bUseGMbetaVariant = GetFieldOrDefault_(strFilterConstConfig, "bUseGMbetaVariant", false);
dDefaultDeltaTstep = GetFieldOrDefault_(strFilterMutabConfig, "dDefaultDeltaTstep", 1.0);

if isfield(strFilterConstConfig.strStatesIdx, "ui8posVelIdx") && numel(strFilterConstConfig.strStatesIdx.ui8posVelIdx) >= 6
    ui16VelIdx = uint16(strFilterConstConfig.strStatesIdx.ui8posVelIdx(4:6));
    dVelocityInputNoiseCov = GetFieldOrDefault_(strFilterMutabConfig, "dVelocityInputNoiseCov", zeros(3));
    [strFilterMutabConfig, ui32NoiseAllocPtr] = AddDirectNoiseBlock_(strFilterMutabConfig, ...
                                                                     ui16VelIdx, ...
                                                                     dVelocityInputNoiseCov, ...
                                                                     ui32NoiseAllocPtr);
end

[strFilterMutabConfig, ui32NoiseAllocPtr] = AddDirectNoiseBlockByField_(strFilterMutabConfig, ...
                                                                        strFilterConstConfig, ...
                                                                        "ui8attBiasDeltaIdx", ...
                                                                        "dAttBiasDeltaInputNoiseCov", ...
                                                                        ui32NoiseAllocPtr);

[strFilterMutabConfig, ui32NoiseAllocPtr] = AddFogmNoiseBlockByField_(strFilterMutabConfig, ...
                                                                      strDynParams, ...
                                                                      strFilterConstConfig, ...
                                                                      "ui8CoeffSRPidx", ...
                                                                      "dCoeffSRPbiasSigma2WN", ...
                                                                      "dCoeffSRPbiasTimeConst", ...
                                                                      dDefaultDeltaTstep, ...
                                                                      bUseGMbetaVariant, ...
                                                                      ui32NoiseAllocPtr);

[strFilterMutabConfig, ui32NoiseAllocPtr] = AddFogmNoiseBlockByField_(strFilterMutabConfig, ...
                                                                      strDynParams, ...
                                                                      strFilterConstConfig, ...
                                                                      "ui8ResidualAccelIdx", ...
                                                                      "dResidualAccelSigma2WN", ...
                                                                      "dResidualAccelTimeConst", ...
                                                                      dDefaultDeltaTstep, ...
                                                                      bUseGMbetaVariant, ...
                                                                      ui32NoiseAllocPtr);

[strFilterMutabConfig, ui32NoiseAllocPtr] = AddFogmNoiseBlockByField_(strFilterMutabConfig, ...
                                                                      strDynParams, ...
                                                                      strFilterConstConfig, ...
                                                                      "ui8LidarMeasBiasIdx", ...
                                                                      "dLidarMeasBiasSigma2WN", ...
                                                                      "dLidarMeasBiasTimeConst", ...
                                                                      dDefaultDeltaTstep, ...
                                                                      bUseGMbetaVariant, ...
                                                                      ui32NoiseAllocPtr);

[strFilterMutabConfig, ui32NoiseAllocPtr] = AddFogmNoiseBlockByField_(strFilterMutabConfig, ...
                                                                      strDynParams, ...
                                                                      strFilterConstConfig, ...
                                                                      "ui8CenMeasBiasIdx", ...
                                                                      "dCenMeasBiasSigma2WN", ...
                                                                      "dCenMeasBiasTimeConst", ...
                                                                      dDefaultDeltaTstep, ...
                                                                      bUseGMbetaVariant, ...
                                                                      ui32NoiseAllocPtr);

[strFilterMutabConfig, ui32NoiseAllocPtr] = AddFogmNoiseBlockByField_(strFilterMutabConfig, ...
                                                                      strDynParams, ...
                                                                      strFilterConstConfig, ...
                                                                      "ui8unmodelAccIdx", ...
                                                                      "dunmAccSigma2WN", ...
                                                                      "dunmAccTimeConst", ...
                                                                      dDefaultDeltaTstep, ...
                                                                      bUseGMbetaVariant, ...
                                                                      ui32NoiseAllocPtr);

[strFilterMutabConfig, ui32NoiseAllocPtr] = AddFogmNoiseBlockByField_(strFilterMutabConfig, ...
                                                                      strDynParams, ...
                                                                      strFilterConstConfig, ...
                                                                      "ui8AImeasBiasIdx", ...
                                                                      "dAImeasBiasSigma2WN", ...
                                                                      "dAImeasBiasTimeConst", ...
                                                                      dDefaultDeltaTstep, ...
                                                                      bUseGMbetaVariant, ...
                                                                      ui32NoiseAllocPtr);

[strFilterMutabConfig, ui32NoiseAllocPtr] = AddFogmNoiseBlockByField_(strFilterMutabConfig, ...
                                                                      strDynParams, ...
                                                                      strFilterConstConfig, ...
                                                                      "ui8CRAmeasBiasIdx", ...
                                                                      "dCRAmeasBiasSigma2WN", ...
                                                                      "dCRAmeasBiasTimeConst", ...
                                                                      dDefaultDeltaTstep, ...
                                                                      bUseGMbetaVariant, ...
                                                                      ui32NoiseAllocPtr);

if isfield(strFilterConstConfig.strStatesIdx, "ui8GravParamIdx")
    ui16GravParamIdx = uint16(strFilterConstConfig.strStatesIdx.ui8GravParamIdx(:));
    dGravParamInputNoiseVar = GetFieldOrDefault_(strFilterMutabConfig, "dGravParamInputNoiseVar", 0.0);
    [strFilterMutabConfig, ui32NoiseAllocPtr] = AddDirectNoiseBlock_(strFilterMutabConfig, ...
                                                                     ui16GravParamIdx, ...
                                                                     dGravParamInputNoiseVar, ...
                                                                     ui32NoiseAllocPtr);
end

if coder.target('MATLAB') || coder.target('MEX')
    assert(ui32NoiseAllocPtr <= uint32(ui8NumInputNoiseChannels) + 1, ...
        'ERROR: input-noise channel allocation exceeded ui8NumOfInputNoiseChannels.');
end

end

%% Internal helper functions for ComputeInputNoise
function [strFilterMutabConfig, ui32NoiseAllocPtr] = AddDirectNoiseBlockByField_(strFilterMutabConfig, ...
                                                                                  strFilterConstConfig, ...
                                                                                  charStateFieldName, ...
                                                                                  charNoiseFieldName, ...
                                                                                  ui32NoiseAllocPtr)
if ~isfield(strFilterConstConfig.strStatesIdx, charStateFieldName)
    return
end

ui16StateIdx = uint16(strFilterConstConfig.strStatesIdx.(charStateFieldName)(:));
if isempty(ui16StateIdx)
    return
end

dBlockNoiseCov = GetFieldOrDefault_(strFilterMutabConfig, ...
                                    charNoiseFieldName, ...
                                    zeros(numel(ui16StateIdx), numel(ui16StateIdx)));

[strFilterMutabConfig, ui32NoiseAllocPtr] = AddDirectNoiseBlock_(strFilterMutabConfig, ...
                                                                 ui16StateIdx, ...
                                                                 dBlockNoiseCov, ...
                                                                 ui32NoiseAllocPtr);
end

function [strFilterMutabConfig, ui32NoiseAllocPtr] = AddFogmNoiseBlockByField_(strFilterMutabConfig, ...
                                                                                strDynParams, ...
                                                                                strFilterConstConfig, ...
                                                                                charStateFieldName, ...
                                                                                charSigmaFieldName, ...
                                                                                charTimeConstFieldName, ...
                                                                                dDefaultDeltaTstep, ...
                                                                                bUseGMbetaVariant, ...
                                                                                ui32NoiseAllocPtr)
if ~isfield(strFilterConstConfig.strStatesIdx, charStateFieldName)
    return
end

ui16StateIdx = uint16(strFilterConstConfig.strStatesIdx.(charStateFieldName)(:));
if isempty(ui16StateIdx)
    return
end

ui32NumStates = uint32(numel(ui16StateIdx));
dSigma2WN = NormalizeVectorField_(GetFieldOrDefault_(strFilterMutabConfig, charSigmaFieldName, zeros(double(ui32NumStates), 1)), ...
                                  ui32NumStates);
dTimeConst = NormalizeVectorField_(GetFieldOrDefault_(strDynParams, charTimeConstFieldName, zeros(double(ui32NumStates), 1)), ...
                                   ui32NumStates);

dBlockNoiseCov = evalMappedProcessNoiseFOGM(dDefaultDeltaTstep, ...
                                            dSigma2WN, ...
                                            dTimeConst, ...
                                            dDefaultDeltaTstep, ...
                                            bUseGMbetaVariant);

[strFilterMutabConfig, ui32NoiseAllocPtr] = AddDirectNoiseBlock_(strFilterMutabConfig, ...
                                                                 ui16StateIdx, ...
                                                                 dBlockNoiseCov, ...
                                                                 ui32NoiseAllocPtr);
end

function [strFilterMutabConfig, ui32NoiseAllocPtr] = AddDirectNoiseBlock_(strFilterMutabConfig, ...
                                                                           ui16StateIdx, ...
                                                                           dBlockNoiseCov, ...
                                                                           ui32NoiseAllocPtr)
ui32NumStates = uint32(numel(ui16StateIdx));
if ui32NumStates == 0
    return
end

ui32BlockEnd = ui32NoiseAllocPtr + ui32NumStates - 1;

if coder.target('MATLAB') || coder.target('MEX')
    assert(ui32BlockEnd <= size(strFilterMutabConfig.dInputProcessNoiseMatrix, 1), ...
        'ERROR: insufficient input-noise channels for the configured state blocks.');
end

dBlockNoiseCov = NormalizeDirectNoiseCov_(dBlockNoiseCov, ui32NumStates);
ui32NoiseRange = ui32NoiseAllocPtr:ui32BlockEnd;

strFilterMutabConfig.dInputProcessNoiseMatrix(ui32NoiseRange, ui32NoiseRange) = dBlockNoiseCov;
strFilterMutabConfig.dProcessNoiseMapMatrix(ui16StateIdx, ui32NoiseRange) = eye(double(ui32NumStates));

ui32NoiseAllocPtr = ui32BlockEnd + 1;
end

function dValue = GetFieldOrDefault_(strInput, charFieldName, dDefaultValue)
if isfield(strInput, charFieldName)
    dValue = strInput.(charFieldName);
else
    dValue = dDefaultValue;
end
end

function dVector = NormalizeVectorField_(dVector, ui32NumStates)
dVector = dVector(:);

if isscalar(dVector) && ui32NumStates > 1
    dVector = repmat(dVector, double(ui32NumStates), 1);
end

if coder.target('MATLAB') || coder.target('MEX')
    assert(numel(dVector) == ui32NumStates, ...
        'ERROR: vector-valued input-noise field does not match the target state block size.');
end

end


function dNoiseCov = NormalizeDirectNoiseCov_(dNoiseCov, ui32NumStates)

if isscalar(dNoiseCov)
    dNoiseCov = double(dNoiseCov) * eye(double(ui32NumStates));
    return
end

dNoiseCov = double(dNoiseCov);

if isvector(dNoiseCov)
    
    dNoiseCov = diag(dNoiseCov(:));
end

if coder.target('MATLAB') || coder.target('MEX')
    assert(all(size(dNoiseCov) == [double(ui32NumStates), double(ui32NumStates)]), ...
        'ERROR: direct input-noise covariance block has incorrect size.');
end
end
