function [strFilterMutabConfig] = UpdateDiscreteFogmInputNoiseForStep(dDeltaTstep, ...
                                                                                      strDynParams, ...
                                                                                      strFilterMutabConfig, ...
                                                                                      strFilterConstConfig) %#codegen
arguments
    dDeltaTstep             (1,1) double {mustBeNumeric, mustBeFinite}
    strDynParams            (1,1) struct
    strFilterMutabConfig    (1,1) struct
    strFilterConstConfig    (1,1) struct {coder.mustBeConst}
end
%% SIGNATURE
% [strFilterMutabConfig] = UpdateDiscreteFogmInputNoiseForStep(dDeltaTstep, ...
%                                                              strDynParams, ...
%                                                              strFilterMutabConfig, ...
%                                                              strFilterConstConfig)
% -------------------------------------------------------------------------------------------------------------
%% DESCRIPTION
% Recompute FOGM input-noise blocks for the current propagation step. The stored dInputProcessNoiseMatrix
% entries are converted to equivalent continuous input intensities, so existing trapezoidal mapped-noise
% integration can remain unchanged and still produce the requested FOGM discrete covariance for dDeltaTstep.
% -------------------------------------------------------------------------------------------------------------

%% Function code
if dDeltaTstep <= eps || coder.const(GetFieldOrDefault_(strFilterConstConfig, 'bOrbitStateOnly', false))
    return
end

if coder.const(~isfield(strFilterConstConfig, 'strStatesIdx') || ~isfield(strFilterMutabConfig, 'dInputProcessNoiseMatrix'))
    return
end

strStatesIdx = strFilterConstConfig.strStatesIdx;
bUseGMbetaVariant = GetFieldOrDefault_(strFilterConstConfig, 'bUseGMbetaVariant', false);
ui32NoiseAllocPtr = uint32(1);

if coder.const(isfield(strStatesIdx, 'ui8posVelIdx') && numel(strStatesIdx.ui8posVelIdx) >= 6)
    ui32NoiseAllocPtr = ui32NoiseAllocPtr + uint32(3);
end

%% Update FOGM input noise blocks for all supported FOGM state types
[strFilterMutabConfig, ui32NoiseAllocPtr] = UpdateFogmBlockByField_(strFilterMutabConfig, ...
                                                                    strDynParams, ...
                                                                    strStatesIdx, ...
                                                                    'ui8attBiasDeltaIdx', ...
                                                                    'dAttBiasDeltaSigma2WN', ...
                                                                    'dAttBiasDeltaTimeConst', ...
                                                                    dDeltaTstep, ...
                                                                    bUseGMbetaVariant, ...
                                                                    ui32NoiseAllocPtr);

[strFilterMutabConfig, ui32NoiseAllocPtr] = UpdateFogmBlockByField_(strFilterMutabConfig, ...
                                                                    strDynParams, ...
                                                                    strStatesIdx, ...
                                                                    'ui8CoeffSRPidx', ...
                                                                    'dCoeffSRPbiasSigma2WN', ...
                                                                    'dCoeffSRPbiasTimeConst', ...
                                                                    dDeltaTstep, ...
                                                                    bUseGMbetaVariant, ...
                                                                    ui32NoiseAllocPtr);

[strFilterMutabConfig, ui32NoiseAllocPtr] = UpdateFogmBlockByField_(strFilterMutabConfig, ...
                                                                    strDynParams, ...
                                                                    strStatesIdx, ...
                                                                    'ui8ResidualAccelIdx', ...
                                                                    'dResidualAccelSigma2WN', ...
                                                                    'dResidualAccelTimeConst', ...
                                                                    dDeltaTstep, ...
                                                                    bUseGMbetaVariant, ...
                                                                    ui32NoiseAllocPtr);

[strFilterMutabConfig, ui32NoiseAllocPtr] = UpdateFogmBlockByField_(strFilterMutabConfig, ...
                                                                    strDynParams, ...
                                                                    strStatesIdx, ...
                                                                    'ui8LidarMeasBiasIdx', ...
                                                                    'dLidarMeasBiasSigma2WN', ...
                                                                    'dLidarMeasBiasTimeConst', ...
                                                                    dDeltaTstep, ...
                                                                    bUseGMbetaVariant, ...
                                                                    ui32NoiseAllocPtr);

[strFilterMutabConfig, ui32NoiseAllocPtr] = UpdateFogmBlockByField_(strFilterMutabConfig, ...
                                                                    strDynParams, ...
                                                                    strStatesIdx, ...
                                                                    'ui8CenMeasBiasIdx', ...
                                                                    'dCenMeasBiasSigma2WN', ...
                                                                    'dCenMeasBiasTimeConst', ...
                                                                    dDeltaTstep, ...
                                                                    bUseGMbetaVariant, ...
                                                                    ui32NoiseAllocPtr);

[strFilterMutabConfig, ui32NoiseAllocPtr] = UpdateFogmBlockByField_(strFilterMutabConfig, ...
                                                                    strDynParams, ...
                                                                    strStatesIdx, ...
                                                                    'ui8unmodelAccIdx', ...
                                                                    'dunmAccSigma2WN', ...
                                                                    'dunmAccTimeConst', ...
                                                                    dDeltaTstep, ...
                                                                    bUseGMbetaVariant, ...
                                                                    ui32NoiseAllocPtr);

[strFilterMutabConfig, ui32NoiseAllocPtr] = UpdateFogmBlockByField_(strFilterMutabConfig, ...
                                                                    strDynParams, ...
                                                                    strStatesIdx, ...
                                                                    'ui8AImeasBiasIdx', ...
                                                                    'dAImeasBiasSigma2WN', ...
                                                                    'dAImeasBiasTimeConst', ...
                                                                    dDeltaTstep, ...
                                                                    bUseGMbetaVariant, ...
                                                                    ui32NoiseAllocPtr);

[strFilterMutabConfig, ~] = UpdateFogmBlockByField_(strFilterMutabConfig, ...
                                                    strDynParams, ...
                                                    strStatesIdx, ...
                                                    'ui8CRAmeasBiasIdx', ...
                                                    'dCRAmeasBiasSigma2WN', ...
                                                    'dCRAmeasBiasTimeConst', ...
                                                    dDeltaTstep, ...
                                                    bUseGMbetaVariant, ...
                                                    ui32NoiseAllocPtr);

% Save the last used deltaTstep for FOGM input noise
if isfield(strFilterMutabConfig, 'dLastProcessNoiseDeltaTstep')
    strFilterMutabConfig.dLastProcessNoiseDeltaTstep = dDeltaTstep;
end

end

%% HELPER FUNCTIONS
function [strFilterMutabConfig, ui32NoiseAllocPtr] = UpdateFogmBlockByField_(strFilterMutabConfig, ...
                                                                              strDynParams, ...
                                                                              strStatesIdx, ...
                                                                              charStateFieldName, ...
                                                                              charSigmaFieldName, ...
                                                                              charTimeConstFieldName, ...
                                                                              dDeltaTstep, ...
                                                                              bUseGMbetaVariant, ...
                                                                              ui32NoiseAllocPtr)
if ~isfield(strStatesIdx, charStateFieldName)
    return
end

ui16StateIdx = uint16(strStatesIdx.(charStateFieldName)(:));
if isempty(ui16StateIdx)
    return
end

ui32NumStates = uint32(numel(ui16StateIdx));
ui32BlockEnd = ui32NoiseAllocPtr + ui32NumStates - uint32(1);

if coder.target('MATLAB') || coder.target('MEX')
    assert(ui32BlockEnd <= size(strFilterMutabConfig.dInputProcessNoiseMatrix, 1), ...
        'ERROR: insufficient input-noise channels for the configured FOGM state block.');
end

if isfield(strFilterMutabConfig, charSigmaFieldName) && isfield(strDynParams, charTimeConstFieldName)
    dSigma2WN = NormalizeVectorField_(strFilterMutabConfig.(charSigmaFieldName), ui32NumStates);
    dTimeConst = NormalizeVectorField_(strDynParams.(charTimeConstFieldName), ui32NumStates);
    dBlockNoiseCov = evalMappedProcessNoiseFOGM(dDeltaTstep, ...
                                                dSigma2WN, ...
                                                dTimeConst, ...
                                                dDeltaTstep, ...
                                                bUseGMbetaVariant) ./ dDeltaTstep;
    ui32NoiseRange = ui32NoiseAllocPtr:ui32BlockEnd;
    strFilterMutabConfig.dInputProcessNoiseMatrix(ui32NoiseRange, ui32NoiseRange) = dBlockNoiseCov;

    if strcmp(charStateFieldName, 'ui8CenMeasBiasIdx') && isfield(strFilterMutabConfig, 'dLastCenMeasBiasInputNoiseDiag')
        strFilterMutabConfig.dLastCenMeasBiasInputNoiseDiag(:) = diag(dBlockNoiseCov);
    end
end

ui32NoiseAllocPtr = ui32BlockEnd + uint32(1);
end

function dValue = GetFieldOrDefault_(strInput, charFieldName, dDefaultValue)
if isfield(strInput, charFieldName)
    dValue = strInput.(charFieldName);
else
    dValue = dDefaultValue;
end
end

function dVector = NormalizeVectorField_(dVector, ui32NumStates)
dVector = dVector(:);

if isscalar(dVector) && ui32NumStates > 1
    dVector = repmat(dVector, double(ui32NumStates), 1);
end

if coder.target('MATLAB') || coder.target('MEX')
    assert(numel(dVector) == ui32NumStates, ...
        'ERROR: vector-valued FOGM input-noise field does not match the target state block size.');
end

end
