classdef testComputeTrapzMappedProcessNoiseCov < matlab.unittest.TestCase
    methods (TestClassSetup)
        function addProjectPaths(~)
            charThisDir = fileparts(mfilename('fullpath'));
            addpath(fullfile(charThisDir, '..', '..', '..', '..'));
            SetupPaths_EstimationGears;
        end
    end

    methods (Test)
        function testTrapezoidalMappedNoiseMatchesClosedForm(testCase)
            dDeltaTstep = 0.25;
            dStateTransitionMat = [1.0, 0.1, 0.0; ...
                                   0.0, 1.0, 0.2; ...
                                   0.0, 0.0, 1.0];
            dProcessNoiseMapMatrix = [1.0, 0.0; ...
                                      0.0, 1.0; ...
                                      1.0, 1.0];
            dInputProcessNoiseMatrix = diag([2.0, 3.0]);

            strFilterConstConfig = struct('ui16StateSize', uint16(3));
            strFilterMutabConfig = struct( ...
                'dProcessNoiseMapMatrix', dProcessNoiseMapMatrix, ...
                'dInputProcessNoiseMatrix', dInputProcessNoiseMatrix, ...
                'bConsiderStatesMode', false(3,1));

            dLLtmatrix = dProcessNoiseMapMatrix * dInputProcessNoiseMatrix * transpose(dProcessNoiseMapMatrix);
            dExpectedQ = 0.5 * dDeltaTstep * ...
                (dLLtmatrix + dStateTransitionMat * dLLtmatrix * transpose(dStateTransitionMat));
            dExpectedQ = 0.5 * (dExpectedQ + transpose(dExpectedQ));

            dQprocessNoiseCov = ComputeTrapzMappedProcessNoiseCov(dDeltaTstep, ...
                                                                  struct(), ...
                                                                  strFilterMutabConfig, ...
                                                                  strFilterConstConfig, ...
                                                                  dStateTransitionMat, ...
                                                                  eye(3));

            testCase.verifyEqual(dQprocessNoiseCov, dExpectedQ, 'AbsTol', 1e-12);
            testCase.verifyEqual(dQprocessNoiseCov, transpose(dQprocessNoiseCov), 'AbsTol', 1e-12);
        end

        function testConsiderStatesAreZeroedBeforeIntegration(testCase)
            dDeltaTstep = 0.5;
            dStateTransitionMat = [1.0, 0.0; 0.2, 1.0];
            dProcessNoiseMapMatrix = eye(2);
            dInputProcessNoiseMatrix = diag([4.0, 5.0]);

            strFilterConstConfig = struct('ui16StateSize', uint16(2));
            strFilterMutabConfig = struct( ...
                'dProcessNoiseMapMatrix', dProcessNoiseMapMatrix, ...
                'dInputProcessNoiseMatrix', dInputProcessNoiseMatrix, ...
                'bConsiderStatesMode', logical([false; true]));

            dLLtmatrix = diag([4.0, 0.0]);
            dExpectedQ = 0.5 * dDeltaTstep * ...
                (dLLtmatrix + dStateTransitionMat * dLLtmatrix * transpose(dStateTransitionMat));
            dExpectedQ = 0.5 * (dExpectedQ + transpose(dExpectedQ));

            dQprocessNoiseCov = ComputeTrapzMappedProcessNoiseCov(dDeltaTstep, ...
                                                                  struct(), ...
                                                                  strFilterMutabConfig, ...
                                                                  strFilterConstConfig, ...
                                                                  dStateTransitionMat, ...
                                                                  eye(2));

            testCase.verifyEqual(dQprocessNoiseCov, dExpectedQ, 'AbsTol', 1e-12);
        end
    end
end
