function [dxPost, dUPost, dDPost] = ComputeGivensRotMeasUpdate_UDCovEKF(dxPrior, ...
                                                                        dUPrior, ...
                                                                        dDPrior, ...
                                                                        dYmeasVec, ...
                                                                        dHobsMatrix, ...
                                                                        bNoPriorInfo, ...
                                                                        bRunPrewhiten, ...
                                                                        dMeasCovSR) %#codegen
arguments
    dxPrior            (:,1) double
    dUPrior            (:,:) double
    dDPrior            (:,:) double
    dYmeasVec              (:,1) double
    dHobsMatrix        (:,:) double
    bNoPriorInfo       (1,1) logical
    bRunPrewhiten     (1,1) logical
    dMeasCovSR         (:,:) double
end
%% SIGNATURE
% [dxPost, dUPost, dDPost] = ComputeGivensRotMeasUpdate_UDCovEKF(dxPrior, ...
%                                                                dUPrior, ...
%                                                                dDPrior, ...
%                                                                dYmeasVec, ...
%                                                                dHobsMatrix, ...
%                                                                bNoPriorInfo, ...
%                                                                bRunPrewhiten, ...
%                                                                dMeasCovSR) %#codegen
% -------------------------------------------------------------------------------------------------------------
%% DESCRIPTION
% UD-covariance EKF measurement update wrapper implemented through the SRIF Givens measurement update.
% `dUPrior` and `dDPrior` represent the prior covariance as P = U * D * U'.
% -------------------------------------------------------------------------------------------------------------
%% CHANGELOG
% 27-04-2026    Pietro Califano     Replace legacy filter-type selector with explicit UD-covariance wrapper.
% -------------------------------------------------------------------------------------------------------------

%% Function code
ui32Nx = uint32(size(dxPrior, 1));

% Input checks (MATLAB/MEX only)
if coder.target('MATLAB') || coder.target('MEX')
    assert(ui32Nx == size(dUPrior, 1) && ui32Nx == size(dUPrior, 2), ...
        'ERROR: mean estimate and U covariance-factor sizes do not match.');
    assert(ui32Nx == size(dDPrior, 1) && ui32Nx == size(dDPrior, 2), ...
        'ERROR: mean estimate and D covariance-factor sizes do not match.');
end

% Initialize the SRIF prior information matrix according to the UD factor convention.
if bNoPriorInfo
    dSRInfoMatPrior = dUPrior;
else
    dSRInfoMatPrior = eye(double(ui32Nx)) / (dUPrior * sqrt(dDPrior));
end

% Execute update using SRIF operations
[dxPost, ~, ~, ~, dSqrtPxPost] = ComputeGivensRotMeasUpdate_SRIF(dxPrior, ...
                                                                 dSRInfoMatPrior, ...
                                                                 dYmeasVec, ...
                                                                 dHobsMatrix, ...
                                                                 bNoPriorInfo, ...
                                                                 bRunPrewhiten, ...
                                                                 dMeasCovSR);

% Reconstruct the UD factors from the SRIF output
dDPost = zeros(double(ui32Nx));
for idState = 1:double(ui32Nx)
    dDPost(idState, idState) = dSqrtPxPost(idState, idState) * dSqrtPxPost(idState, idState);
end

dUPost = dSqrtPxPost / (eye(double(ui32Nx)) .* diag(dSqrtPxPost));

end
