function [strOrbitData, strFitStats, dSampleTimestamps, dSamplePositions_IN] = ...
    BuildClosedLoopCameraEphemeridesOrbitData(dxState, ...
                                              dStateTimetag, ...
                                              dStartTimestamp, ...
                                              dStopTimestamp, ...
                                              dIntegrTimestep, ...
                                              strDynParams, ...
                                              strFilterMutabConfig, ...
                                              strFilterConstConfig, ...
                                              ui32PolyDeg, ...
                                              ui32MinSamples, ...
                                              ui32MaxSamples, ...
                                              dPreferredSampleStepSec, ...
                                              ui32GenerationManoeuvreCounter, ...
                                              bEnableFitCheck, ...
                                              dFitPercRelErrorTol, ...
                                              charSource)%#codegen
%% SIGNATURE
% [strOrbitData, strFitStats, dSampleTimestamps, dSamplePositions_IN] = ...
%     BuildClosedLoopCameraEphemeridesOrbitData(dxState, dStateTimetag, ...
%                                               dStartTimestamp, dStopTimestamp, ...
%                                               dIntegrTimestep, strDynParams, ...
%                                               strFilterMutabConfig, ...
%                                               strFilterConstConfig, ...
%                                               ui32PolyDeg, ui32MinSamples, ...
%                                               ui32MaxSamples, ...
%                                               dPreferredSampleStepSec, ...
%                                               ui32GenerationManoeuvreCounter, ...
%                                               bEnableFitCheck, ...
%                                               dFitPercRelErrorTol, ...
%                                               charSource)
% -------------------------------------------------------------------------------------------------------------
%% DESCRIPTION
% Build a camera-position Chebyshev ephemeris pack by propagating filter dynamics.
% The returned struct follows the existing SimulationGears/MathCore `strOrbitData`
% contract consumed by `evalChbvPolyWithCoeffs`.
% -------------------------------------------------------------------------------------------------------------
%% INPUT
% dxState                         Current filter state at dStateTimetag.
% dStateTimetag                   State timestamp [s].
% dStartTimestamp                 First ephemerides validity timestamp [s].
% dStopTimestamp                  Last ephemerides validity timestamp [s].
% dIntegrTimestep                 PropagateDyn integration step [s].
% strDynParams                    Dynamics parameter struct.
% strFilterMutabConfig            Mutable filter configuration struct.
% strFilterConstConfig            Constant filter configuration struct.
% ui32PolyDeg                     Chebyshev polynomial degree. Default: 10.
% ui32MinSamples                  Minimum fit samples. Default: 16.
% ui32MaxSamples                  Maximum fit samples. Default: 128.
% dPreferredSampleStepSec         Preferred sample spacing [s]. Default: 300.
% ui32GenerationManoeuvreCounter  Manoeuvre counter used to tag pack validity. Default: 0.
% bEnableFitCheck                 Enable fit validation in fitChbvPolynomials. Default: true.
% dFitPercRelErrorTol             Fit relative-error tolerance [%]. Default: 0.1.
% charSource                      Source tag stored in output struct. Default: 'filter_dynamics'.
% -------------------------------------------------------------------------------------------------------------
%% OUTPUT
% strOrbitData                    Codegen-compatible camera ephemerides orbit-data struct.
% strFitStats                     Chebyshev fit diagnostics from fitChbvPolynomials.
% dSampleTimestamps               Sample timestamps used for fitting [s].
% dSamplePositions_IN             Sample camera positions used for fitting.
% -------------------------------------------------------------------------------------------------------------
%% CHANGELOG
% 02-05-2026    Pietro Califano, Codex     First implementation for autonomous generation of ephemerides pack 
%                                          from best on-board knowledge
% -------------------------------------------------------------------------------------------------------------
%% DEPENDENCIES
% PropagateDyn
% fitChbvPolynomials
% -------------------------------------------------------------------------------------------------------------
arguments
    dxState              (:,1) double
    dStateTimetag        (1,1) double
    dStartTimestamp      (1,1) double
    dStopTimestamp       (1,1) double
    dIntegrTimestep      (1,1) double
    strDynParams         (1,1) struct
    strFilterMutabConfig (1,1) struct
    strFilterConstConfig (1,1) struct
    ui32PolyDeg                    (1,1) uint32 = uint32(10)
    ui32MinSamples                 (1,1) uint32 = uint32(16)
    ui32MaxSamples                 (1,1) uint32 = uint32(128)
    dPreferredSampleStepSec        (1,1) double = 300.0
    ui32GenerationManoeuvreCounter (1,1) uint32 = uint32(0)
    bEnableFitCheck                (1,1) logical = true
    dFitPercRelErrorTol            (1,1) double = 0.1
    charSource                     (1,:) char = 'filter_dynamics'
end

%% Function code
if ui32PolyDeg < uint32(2)
    error('EstimationGears:InvalidPointingEphemeridesDegree', ...
          'Pointing ephemerides polynomial degree must be at least 2.');
end

if dStopTimestamp <= dStartTimestamp
    error('EstimationGears:InvalidPointingEphemeridesDomain', ...
          'Pointing ephemerides stop timestamp must be greater than start timestamp.');
end

if dIntegrTimestep <= 0.0
    error('EstimationGears:InvalidPointingEphemeridesIntegratorStep', ...
          'Pointing ephemerides integrator timestep must be positive.');
end

% Compute number of samples based on preferred step and limits
dHorizonSec = dStopTimestamp - dStartTimestamp;
ui32RequestedSamples = uint32(ceil(dHorizonSec / max(dPreferredSampleStepSec, eps('double')))) + uint32(1);
ui32RequiredSamples = max(ui32MinSamples, ui32PolyDeg + uint32(1));
ui32NumSamples = max(ui32RequiredSamples, min(ui32MaxSamples, ui32RequestedSamples));

% Build sample timegrid and matrix
dSampleTimestamps = linspace(dStartTimestamp, dStopTimestamp, double(ui32NumSamples));
dSamplePositions_IN = zeros(3, double(ui32NumSamples));

% Fetch initial state and propagate to first sample if needed
dxPropState = dxState(1:strFilterConstConfig.ui16StateSize);
dPropTimetag = dStateTimetag;
strPropDynParams = strDynParams;

if abs(dStartTimestamp - dPropTimetag) > eps('double')
    [dxPropState, dPropTimetag, strPropDynParams] = PropagateDyn(dxPropState, ...
                                                                 dPropTimetag, ...
                                                                 dStartTimestamp - dPropTimetag, ...
                                                                 dIntegrTimestep, ...
                                                                 strPropDynParams, ...
                                                                 strFilterMutabConfig, ...
                                                                 strFilterConstConfig);
end

% Propagate and sample states at timegrid epochs using nav-system dynamics and knowlege
for ui32SampleIdx = 1:ui32NumSamples
    dSampleTimestamp = dSampleTimestamps(ui32SampleIdx);

    if abs(dSampleTimestamp - dPropTimetag) > eps('double')
        [dxPropState, dPropTimetag, strPropDynParams] = PropagateDyn(dxPropState, ...
                                                                     dPropTimetag, ...
                                                                     dSampleTimestamp - dPropTimetag, ...
                                                                     dIntegrTimestep, ...
                                                                     strPropDynParams, ...
                                                                     strFilterMutabConfig, ...
                                                                     strFilterConstConfig);
    end

    dSamplePositions_IN(:, ui32SampleIdx) = dxPropState(strFilterConstConfig.strStatesIdx.ui8posVelIdx(1:3));
end

% Fit Chebyshev polynomial to propagated samples and build output struct (nav-system format)
[dChbvCoeffs, ~, strFitStats] = fitChbvPolynomials(ui32PolyDeg, ...
                                                   dSampleTimestamps(:), ...
                                                   dSamplePositions_IN, ...
                                                   dStartTimestamp, ...
                                                   dStopTimestamp, ...
                                                   bEnableFitCheck, ...
                                                   false, ...
                                                   dFitPercRelErrorTol);

bFitValid = true;
if bEnableFitCheck && isfield(strFitStats, 'dMaxRelErr') && isfield(strFitStats, 'dAvgRelErr')
    bFitValid = all([strFitStats.dMaxRelErr, max(strFitStats.dAvgRelErr)] <= dFitPercRelErrorTol);
end

strOrbitData = struct('bValid', true, ...
                      'charSource', charSource, ...
                      'ui32GenerationManoeuvreCounter', ui32GenerationManoeuvreCounter, ...
                      'ui32PolyDeg', ui32PolyDeg, ...
                      'dChbvPolycoeffs', dChbvCoeffs, ...
                      'dTimeLowBound', dStartTimestamp, ...
                      'dTimeUpBound', dStopTimestamp, ...
                      'ui32NumFitSamples', ui32NumSamples, ...
                      'dPreferredSampleStepSec', dPreferredSampleStepSec);
strOrbitData.bValid = bFitValid;
end
