function [dxStateNext, dStateTimetag, strDynParams] = PropagateDyn(dxState, ...
                                                                   dStateTimetag, ...
                                                                   dDeltaTime, ...
                                                                   dIntegrTimeStep, ...
                                                                   strDynParams, ...
                                                                   strFilterMutabConfig, ...
                                                                   strFilterConstConfig) %#codegen
arguments
    dxState                 (:,1) double {mustBeNumeric}
    dStateTimetag           (1,1) double {mustBeNumeric}
    dDeltaTime              (1,1) double {mustBeNumeric}
    dIntegrTimeStep         (1,1) double {mustBeNumeric}
    strDynParams            (1,1) struct
    strFilterMutabConfig    (1,1) struct
    strFilterConstConfig    (1,1) struct {coder.mustBeConst}
end
%% PROTOTYPE
% [dxStateNext, dStateTimetag, strDynParams] = PropagateDyn(dxState, ...
%                                                           dStateTimetag, ...
%                                                           dDeltaTime, ...
%                                                           dIntegrTimeStep, ...
%                                                           strDynParams, ...
%                                                           strFilterMutabConfig, ...
%                                                           strFilterConstConfig) %#codegen
% -------------------------------------------------------------------------------------------------------------
%% DESCRIPTION
% Generic shared flow function propagating the state forward or backward in time using the configured
% dynamics RHS and RK4 integrator.
% -------------------------------------------------------------------------------------------------------------
%% CHANGELOG
% 22-04-2026    Pietro Califano     Add generic shared propagation wrapper with standard signature.
% 23-04-2026    Pietro Califano     Preserve the existing three-output call pattern used by the EKF modules.
% -------------------------------------------------------------------------------------------------------------

[dxStateNext, dStateTimetag] = IntegratorStepRK4(dxState, ...
                                                 dStateTimetag, ...
                                                 dDeltaTime, ...
                                                 dIntegrTimeStep, ...
                                                 strDynParams, ...
                                                 strFilterMutabConfig, ...
                                                 strFilterConstConfig);

end
