classdef testCommonSigmaPointTemplateComparison < matlab.unittest.TestCase
    methods (TestClassSetup)
        function addProjectPaths(~)
            SetupPaths_EstimationGears;

            charThisDir = fileparts(mfilename('fullpath'));
            charHelpersDir = fullfile(charThisDir, '..', 'test_helpers', 'helpers_mocks');
            addpath(genpath(charHelpersDir), '-begin');
        end
    end

    methods (Test)
        function testCommonAdditiveObsUpdate_AgreesAcrossSquareRootAndUDForms(testCase)
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0; 3.0], ...
                                                               diag([0.4, 0.4, 0.2]), ...
                                                               [1.2; 1.8], ...
                                                               uint16([1; 2]));

            [dxStatePostSR, dStateSqrtCovPostSR, ~, ~, dResidualSR, dKalmanGainSR, dxErrStateSR, dSqrtSyySR] = ...
                SR_UKF_ObsUp(strProblem.dxState, ...
                             strProblem.dStateSqrtCov, ...
                             strProblem.dStateTimetag, ...
                             strProblem.dxSigmaPoints, ...
                             strProblem.strMeasBus, ...
                             strProblem.strDynParams, ...
                             strProblem.strMeasModelParams, ...
                             strProblem.strFilterMutabConfig, ...
                             strProblem.strFilterConstConfig);

            [dUprior, dDprior] = UDdecomposition(strProblem.dStateCov);
            [dxStatePostUD, dUpostUD, dDpostUD, ~, ~, dResidualUD, dKalmanGainUD, dxErrStateUD, dPyyResCovUD] = ...
                SR_UKF_UDCov_ObsUp(strProblem.dxState, ...
                                   dUprior, ...
                                   dDprior, ...
                                   strProblem.dStateTimetag, ...
                                   strProblem.dxSigmaPoints, ...
                                   strProblem.strMeasBus, ...
                                   strProblem.strDynParams, ...
                                   strProblem.strMeasModelParams, ...
                                   strProblem.strFilterMutabConfig, ...
                                   strProblem.strFilterConstConfig);

            dStateCovPostSR = dStateSqrtCovPostSR' * dStateSqrtCovPostSR;
            dStateCovPostUD = dUpostUD * dDpostUD * dUpostUD';
            dPyyResCovSR = dSqrtSyySR' * dSqrtSyySR;

            testCase.verifyEqual(dxStatePostUD, dxStatePostSR, 'AbsTol', 1e-10);
            testCase.verifyEqual(dResidualUD, dResidualSR, 'AbsTol', 1e-10);
            testCase.verifyEqual(dKalmanGainUD, dKalmanGainSR, 'AbsTol', 1e-10);
            testCase.verifyEqual(dxErrStateUD, dxErrStateSR, 'AbsTol', 1e-10);
            testCase.verifyEqual(dStateCovPostUD, dStateCovPostSR, 'AbsTol', 1e-10);
            testCase.verifyEqual(dPyyResCovUD, dPyyResCovSR, 'AbsTol', 1e-10);
        end

        function testCommonTailoredObsUpdate_AgreesAcrossSquareRootAndUDForms(testCase)
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0; 3.0], ...
                                                               diag([0.4, 0.4, 0.2]), ...
                                                               [1.2; 1.8], ...
                                                               uint16([1; 2]), ...
                                                               enumResidualMode=EnumSigmaPointResidualMode.TAILORED);

            [dxStatePostSR, dStateSqrtCovPostSR, ~, ~, dResidualSR, dKalmanGainSR, dxErrStateSR, dSqrtSyySR] = ...
                SR_UKF_ObsUp(strProblem.dxState, ...
                             strProblem.dStateSqrtCov, ...
                             strProblem.dStateTimetag, ...
                             strProblem.dxSigmaPoints, ...
                             strProblem.strMeasBus, ...
                             strProblem.strDynParams, ...
                             strProblem.strMeasModelParams, ...
                             strProblem.strFilterMutabConfig, ...
                             strProblem.strFilterConstConfig);

            [dUprior, dDprior] = UDdecomposition(strProblem.dStateCov);
            [dxStatePostUD, dUpostUD, dDpostUD, ~, ~, dResidualUD, dKalmanGainUD, dxErrStateUD, dPyyResCovUD] = ...
                SR_UKF_UDCov_ObsUp(strProblem.dxState, ...
                                   dUprior, ...
                                   dDprior, ...
                                   strProblem.dStateTimetag, ...
                                   strProblem.dxSigmaPoints, ...
                                   strProblem.strMeasBus, ...
                                   strProblem.strDynParams, ...
                                   strProblem.strMeasModelParams, ...
                                   strProblem.strFilterMutabConfig, ...
                                   strProblem.strFilterConstConfig);

            dStateCovPostSR = dStateSqrtCovPostSR' * dStateSqrtCovPostSR;
            dStateCovPostUD = dUpostUD * dDpostUD * dUpostUD';
            dPyyResCovSR = dSqrtSyySR' * dSqrtSyySR;

            testCase.verifyEqual(dxStatePostUD, dxStatePostSR, 'AbsTol', 1e-10);
            testCase.verifyEqual(dResidualUD, dResidualSR, 'AbsTol', 1e-10);
            testCase.verifyEqual(dKalmanGainUD, dKalmanGainSR, 'AbsTol', 1e-10);
            testCase.verifyEqual(dxErrStateUD, dxErrStateSR, 'AbsTol', 1e-10);
            testCase.verifyEqual(dStateCovPostUD, dStateCovPostSR, 'AbsTol', 1e-10);
            testCase.verifyEqual(dPyyResCovUD, dPyyResCovSR, 'AbsTol', 1e-10);
        end
    end
end
