classdef testSR_UKF_step < matlab.unittest.TestCase
    methods (TestClassSetup)
        function addProjectPaths(~)
            SetupPaths_EstimationGears;

            charThisDir = fileparts(mfilename('fullpath'));
            charHelpersDir = fullfile(charThisDir, '..', 'test_helpers', 'helpers_mocks');
            addpath(genpath(charHelpersDir), '-begin');
        end
    end

    methods (Test)
        function testStepRunsTimeUpdateOnlyWhenNoMeasurement(testCase)
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0; 3.0], ...
                                                               diag([0.4, 0.3, 0.2]), ...
                                                               [1.0; 2.0], ...
                                                               uint16([1; 2]));

            [strOutput, dxState, dSqrtCov, dStateTimetag] = SR_UKF_step(strProblem.dxState, ...
                                                                        strProblem.dStateSqrtCov, ...
                                                                        strProblem.dStateTimetag, ...
                                                                        0.5, ...
                                                                        strProblem.strMeasBus, ...
                                                                        strProblem.strMeasModelParams, ...
                                                                        strProblem.strDynParams, ...
                                                                        strProblem.strFilterMutabConfig, ...
                                                                        strProblem.strFilterConstConfig);

            testCase.verifyEqual(dxState, strProblem.dxState + 0.5, 'AbsTol', 1e-8);
            testCase.verifyEqual(dSqrtCov' * dSqrtCov, strProblem.dStateCov, 'AbsTol', 1e-8);
            testCase.verifyEqual(dStateTimetag, 0.5, 'AbsTol', 1e-12);
            testCase.verifyEqual(strOutput.dMeasUpdateTimetag, 0.0, 'AbsTol', 1e-12);
            testCase.verifyEqual(strOutput.dxStatePrior, dxState, 'AbsTol', 1e-8);
        end

        function testStepObservationUpdateMatchesDirectObsUp(testCase)
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0; 3.0], ...
                                                               diag([0.4, 0.4, 0.2]), ...
                                                               [1.2; 1.8], ...
                                                               uint16([1; 2]));
            strFilterMutabConfig = strProblem.strFilterMutabConfig;
            strFilterMutabConfig.bNewMeasAvailable = true;

            [dxStateRef, dSqrtRef, ~, ~, dResidualRef, dKalmanGainRef, dxErrStateRef, dSqrtSyyRef] = ...
                SR_UKF_ObsUp(strProblem.dxState, ...
                             strProblem.dStateSqrtCov, ...
                             strProblem.dStateTimetag, ...
                             strProblem.dxSigmaPoints, ...
                             strProblem.strMeasBus, ...
                             strProblem.strDynParams, ...
                             strProblem.strMeasModelParams, ...
                             strFilterMutabConfig, ...
                             strProblem.strFilterConstConfig);

            [strOutput, dxState, dSqrtCov, dStateTimetag] = SR_UKF_step(strProblem.dxState, ...
                                                                        strProblem.dStateSqrtCov, ...
                                                                        strProblem.dStateTimetag, ...
                                                                        strProblem.dStateTimetag, ...
                                                                        strProblem.strMeasBus, ...
                                                                        strProblem.strMeasModelParams, ...
                                                                        strProblem.strDynParams, ...
                                                                        strFilterMutabConfig, ...
                                                                        strProblem.strFilterConstConfig);

            testCase.verifyEqual(dxState, dxStateRef, 'AbsTol', 1e-10);
            testCase.verifyEqual(dSqrtCov, dSqrtRef, 'AbsTol', 1e-10);
            testCase.verifyEqual(dStateTimetag, strProblem.dStateTimetag, 'AbsTol', 1e-12);
            testCase.verifyEqual(strOutput.dAllPriorResVector(1:2), dResidualRef, 'AbsTol', 1e-10);
            testCase.verifyEqual(strOutput.dKalmanGain(:, 1:2), dKalmanGainRef, 'AbsTol', 1e-10);
            testCase.verifyEqual(strOutput.dxErrState, dxErrStateRef, 'AbsTol', 1e-10);
            testCase.verifyEqual(strOutput.dSqrtSyyResCov(1:2, 1:2), dSqrtSyyRef, 'AbsTol', 1e-10);
            testCase.verifyEqual(strOutput.dMeasUpdateTimetag, strProblem.dStateTimetag, 'AbsTol', 1e-12);
        end
    end
end
