classdef testSR_UKF_ObsUp < matlab.unittest.TestCase
    methods (TestClassSetup)
        function addProjectPaths(~)
            SetupPaths_EstimationGears;

            charThisDir = fileparts(mfilename('fullpath'));
            charHelpersDir = fullfile(charThisDir, '..', 'test_helpers', 'helpers_mocks');
            addpath(genpath(charHelpersDir), '-begin');
        end
    end

    methods (Test)
        function testBuilderProvidesExplicitSigmaPointRuntimeFields(testCase)
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0; 3.0], ...
                                                               diag([0.4, 0.4, 0.2]), ...
                                                               [1.2; 1.8], ...
                                                               uint16([1; 2]));

            strFilterMutabConfig = strProblem.strFilterMutabConfig;
            strFilterConstConfig = strProblem.strFilterConstConfig;

            testCase.verifyTrue(isfield(strFilterMutabConfig, 'dSqrtRmeasNoiseCov'));
            testCase.verifyTrue(isfield(strFilterMutabConfig, 'dSqrtQprocessNoiseCov'));
            testCase.verifyTrue(isfield(strFilterMutabConfig, 'dUnscentedWeightsMean'));
            testCase.verifyTrue(isfield(strFilterMutabConfig, 'dUnscentedWeightsCov'));
            testCase.verifyTrue(isfield(strFilterMutabConfig, 'dSqrtWmWc'));
            testCase.verifyTrue(isfield(strFilterMutabConfig, 'dPerturbScale'));
            testCase.verifyTrue(isfield(strFilterConstConfig, 'enumSigmaPointResidualMode'));
        end

        function testTailoredMeasurementUpdateRuns(testCase)
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0; 3.0], ...
                                                               diag([0.4, 0.4, 0.2]), ...
                                                               [1.2; 1.8], ...
                                                               uint16([1; 2]));

            [dxStatePost, dStateSqrtCovPost, ~, ~, dResidual, dKalmanGain, dxErrState, dSqrtSyy] = ...
                SR_UKF_ObsUp(strProblem.dxState, ...
                             strProblem.dStateSqrtCov, ...
                             strProblem.dStateTimetag, ...
                             strProblem.dxSigmaPoints, ...
                             strProblem.strMeasBus, ...
                             strProblem.strDynParams, ...
                             strProblem.strMeasModelParams, ...
                             strProblem.strFilterMutabConfig, ...
                             strProblem.strFilterConstConfig);

            testCase.verifyGreaterThan(dxStatePost(1), strProblem.dxState(1));
            testCase.verifyLessThan(dxStatePost(2), strProblem.dxState(2));
            testCase.verifyEqual(dxStatePost(3), strProblem.dxState(3), 'AbsTol', 1e-12);
            testCase.verifyEqual(dResidual, [0.2; -0.2], 'AbsTol', 1e-9);
            testCase.verifyTrue(istriu(dStateSqrtCovPost));
            testCase.verifyTrue(istriu(dSqrtSyy(1:2, 1:2)));
            testCase.verifyTrue(any(abs(dKalmanGain(:, 1:2)) > 0, 'all'));
            testCase.verifyTrue(any(abs(dxErrState(1:2)) > 0));
        end

        function testTailoredResidualPolicyRuns(testCase)
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0; 3.0], ...
                                                               diag([0.4, 0.4, 0.2]), ...
                                                               [1.2; 1.8], ...
                                                               uint16([1; 2]), ...
                                                               enumResidualMode=EnumSigmaPointResidualMode.TAILORED);

            [dxStatePost, ~, ~, ~, dResidual] = SR_UKF_ObsUp(strProblem.dxState, ...
                                                              strProblem.dStateSqrtCov, ...
                                                              strProblem.dStateTimetag, ...
                                                              strProblem.dxSigmaPoints, ...
                                                              strProblem.strMeasBus, ...
                                                              strProblem.strDynParams, ...
                                                              strProblem.strMeasModelParams, ...
                                                              strProblem.strFilterMutabConfig, ...
                                                              strProblem.strFilterConstConfig);

            testCase.verifyEqual(dResidual, [0.2; -0.2], 'AbsTol', 1e-9);
            testCase.verifyGreaterThan(dxStatePost(1), strProblem.dxState(1));
            testCase.verifyLessThan(dxStatePost(2), strProblem.dxState(2));
        end

        function testMeasurementEditingCanRejectUpdate(testCase)
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0], ...
                                                               0.1 * eye(2), ...
                                                               [10.0; 10.0], ...
                                                               uint16([1; 2]), ...
                                                               bEnableEditing=true, ...
                                                               dMahaDist2MeasThr=1.0, ...
                                                               ui32MaxNumMeasEditing=uint32(1), ...
                                                               dMeasNoiseVariance=0.01);

            [dxStatePost, ~, ~, strFilterMutabConfig] = SR_UKF_ObsUp(strProblem.dxState, ...
                                                                      strProblem.dStateSqrtCov, ...
                                                                      strProblem.dStateTimetag, ...
                                                                      strProblem.dxSigmaPoints, ...
                                                                      strProblem.strMeasBus, ...
                                                                      strProblem.strDynParams, ...
                                                                      strProblem.strMeasModelParams, ...
                                                                      strProblem.strFilterMutabConfig, ...
                                                                      strProblem.strFilterConstConfig);

            testCase.verifyEqual(dxStatePost, strProblem.dxState, 'AbsTol', 1e-12);
            testCase.verifyEqual(strFilterMutabConfig.ui32MeasEditingCounter, uint32(1));
        end

        function testConsiderStatesModeFreezesSelectedState(testCase)
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0; 3.0], ...
                                                               [0.4, 0.08, 0.02; ...
                                                                0.08, 0.5, 0.03; ...
                                                                0.02, 0.03, 0.2], ...
                                                               [1.2; 1.8], ...
                                                               uint16([1; 2]), ...
                                                               bConsiderStatesMode=logical([false; true; false]));

            [dxStatePost, dStateSqrtCovPost, ~, ~, ~, dKalmanGain, dxErrState, dSqrtSyy] = ...
                SR_UKF_ObsUp(strProblem.dxState, ...
                             strProblem.dStateSqrtCov, ...
                             strProblem.dStateTimetag, ...
                             strProblem.dxSigmaPoints, ...
                             strProblem.strMeasBus, ...
                             strProblem.strDynParams, ...
                             strProblem.strMeasModelParams, ...
                             strProblem.strFilterMutabConfig, ...
                             strProblem.strFilterConstConfig);

            dStateCovPost = dStateSqrtCovPost' * dStateSqrtCovPost;
            dPyy = dSqrtSyy(1:2, 1:2)' * dSqrtSyy(1:2, 1:2);
            dConsiderGain = zeros(size(dKalmanGain(:, 1:2)));
            dConsiderGain(2, :) = dKalmanGain(2, 1:2);
            
            dExpectedStateCovPost = strProblem.dStateCov ...
                - dKalmanGain(:, 1:2) * dPyy * dKalmanGain(:, 1:2)' ...
                + dConsiderGain * dPyy * dConsiderGain';
            dExpectedStateCovPost = 0.5 .* (dExpectedStateCovPost + dExpectedStateCovPost');

            testCase.verifyEqual(dxErrState(2), 0.0, 'AbsTol', 1e-12);
            testCase.verifyEqual(dxStatePost(2), strProblem.dxState(2), 'AbsTol', 1e-12);
            testCase.verifyEqual(dStateCovPost(2, 2), strProblem.dStateCov(2, 2), 'AbsTol', 1e-12);
            testCase.verifyEqual(dStateCovPost, dExpectedStateCovPost, 'AbsTol', 1e-10);
            testCase.verifyGreaterThan(abs(dStateCovPost(1, 2) - strProblem.dStateCov(1, 2)), 1e-12);
        end

        function testBuiltInAdaptivityFlagsDoNotMutateNoiseFactors(testCase)
            dProcessNoiseCov = 0.05 * eye(6);
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0; 3.0; 4.0; 5.0; 6.0], ...
                                                               diag([0.4, 0.4, 0.2, 0.3, 0.3, 0.3]), ...
                                                               [1.5; 1.2], ...
                                                               uint16([1; 2]), ...
                                                               bEnableAdaptivity=true, ...
                                                               bAdaptMeasNoiseCov=true, ...
                                                               bAdaptProcessNoiseCov=true, ...
                                                               dAdaptiveNoiseAlpha=0.6, ...
                                                               dMeasNoiseVariance=0.02, ...
                                                               dProcessNoiseCov=dProcessNoiseCov);

            dInitialSqrtR = strProblem.strFilterMutabConfig.dSqrtRmeasNoiseCov;
            dInitialSqrtQ = strProblem.strFilterMutabConfig.dSqrtQprocessNoiseCov;

            [~, ~, ~, strFilterMutabConfig, dResidual, dKalmanGain, dxErrState, dSqrtSyy] = ...
                SR_UKF_ObsUp(strProblem.dxState, ...
                             strProblem.dStateSqrtCov, ...
                             strProblem.dStateTimetag, ...
                             strProblem.dxSigmaPoints, ...
                             strProblem.strMeasBus, ...
                             strProblem.strDynParams, ...
                             strProblem.strMeasModelParams, ...
                             strProblem.strFilterMutabConfig, ...
                             strProblem.strFilterConstConfig);

            testCase.verifyTrue(istriu(strFilterMutabConfig.dSqrtRmeasNoiseCov));
            testCase.verifyTrue(istriu(strFilterMutabConfig.dSqrtQprocessNoiseCov));
            testCase.verifyEqual(strFilterMutabConfig.dSqrtRmeasNoiseCov, dInitialSqrtR, 'AbsTol', 1e-12);
            testCase.verifyEqual(strFilterMutabConfig.dSqrtQprocessNoiseCov, dInitialSqrtQ, 'AbsTol', 1e-12);
            testCase.verifyGreaterThan(norm(dResidual, 2), 0.0);
            testCase.verifyGreaterThan(norm(dKalmanGain, 'fro'), 0.0);
            testCase.verifyGreaterThan(norm(dxErrState, 2), 0.0);
            testCase.verifyTrue(istriu(dSqrtSyy(1:2, 1:2)));
        end

        function testLatencyMismatchRaisesExplicitError(testCase)
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0; 3.0], ...
                                                               diag([0.4, 0.4, 0.2]), ...
                                                               [1.2; 1.8], ...
                                                               uint16([1; 2]), ...
                                                               dMeasTimetags=[0.5; 0.5]);

            testCase.verifyError(@() SR_UKF_ObsUp(strProblem.dxState, ...
                                                  strProblem.dStateSqrtCov, ...
                                                  strProblem.dStateTimetag, ...
                                                  strProblem.dxSigmaPoints, ...
                                                  strProblem.strMeasBus, ...
                                                  strProblem.strDynParams, ...
                                                  strProblem.strMeasModelParams, ...
                                                  strProblem.strFilterMutabConfig, ...
                                                  strProblem.strFilterConstConfig), ...
                                 'SR_UKF_ObsUp:UnsupportedLatency');
        end
    end
end
