classdef testSR_UKF_Adaptive_ObsUp < matlab.unittest.TestCase
    methods (TestClassSetup)
        function addProjectPaths(~)
            SetupPaths_EstimationGears;

            charThisDir = fileparts(mfilename('fullpath'));
            charHelpersDir = fullfile(charThisDir, '..', 'test_helpers', 'helpers_mocks');
            addpath(genpath(charHelpersDir), '-begin');
        end
    end

    methods (Test)
        function testBuilderProvidesExplicitSigmaPointRuntimeFields(testCase)
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0; 3.0], ...
                                                               diag([0.4, 0.4, 0.2]), ...
                                                               [1.2; 1.8], ...
                                                               uint16([1; 2]));

            strFilterMutabConfig = strProblem.strFilterMutabConfig;
            strFilterConstConfig = strProblem.strFilterConstConfig;

            testCase.verifyTrue(isfield(strFilterMutabConfig, 'dsqrtRmeasNoiseCov'));
            testCase.verifyTrue(isfield(strFilterMutabConfig, 'dsqrtQprocessNoiseCov'));
            testCase.verifyTrue(isfield(strFilterMutabConfig, 'dUnscentedWeightsMean'));
            testCase.verifyTrue(isfield(strFilterMutabConfig, 'dUnscentedWeightsCov'));
            testCase.verifyTrue(isfield(strFilterMutabConfig, 'dsqrtWmWc'));
            testCase.verifyTrue(isfield(strFilterMutabConfig, 'dPerturbScale'));
            testCase.verifyTrue(isfield(strFilterConstConfig, 'enumSigmaPointResidualMode'));

            testCase.verifyFalse(isfield(strFilterMutabConfig, 'dSqrtRmeasNoiseCov'));
            testCase.verifyFalse(isfield(strFilterMutabConfig, 'dSqrtQprocessNoiseCov'));
            testCase.verifyFalse(isfield(strFilterMutabConfig, 'strFilterParams'));
        end

        function testTailoredMeasurementUpdateRuns(testCase)
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0; 3.0], ...
                                                               diag([0.4, 0.4, 0.2]), ...
                                                               [1.2; 1.8], ...
                                                               uint16([1; 2]));

            [dxStatePost, dStateSqrtCovPost, ~, ~, dResidual, dKalmanGain, dxErrState, dSqrtSyy] = ...
                SR_UKF_Adaptive_ObsUp(strProblem.dxState, ...
                                      strProblem.dStateSqrtCov, ...
                                      strProblem.dStateTimetag, ...
                                      strProblem.dxSigmaPoints, ...
                                      strProblem.strMeasBus, ...
                                      strProblem.strDynParams, ...
                                      strProblem.strMeasModelParams, ...
                                      strProblem.strFilterMutabConfig, ...
                                      strProblem.strFilterConstConfig);

            testCase.verifyGreaterThan(dxStatePost(1), strProblem.dxState(1));
            testCase.verifyLessThan(dxStatePost(2), strProblem.dxState(2));
            testCase.verifyEqual(dxStatePost(3), strProblem.dxState(3), 'AbsTol', 1e-12);
            testCase.verifyEqual(dResidual, [0.2; -0.2], 'AbsTol', 1e-9);
            testCase.verifyTrue(istriu(dStateSqrtCovPost));
            testCase.verifyTrue(istriu(dSqrtSyy(1:2, 1:2)));
            testCase.verifyTrue(any(abs(dKalmanGain(:, 1:2)) > 0, 'all'));
            testCase.verifyTrue(any(abs(dxErrState(1:2)) > 0));
        end

        function testTailoredResidualPolicyRuns(testCase)
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0; 3.0], ...
                                                               diag([0.4, 0.4, 0.2]), ...
                                                               [1.2; 1.8], ...
                                                               uint16([1; 2]), ...
                                                               enumResidualMode=EnumSigmaPointResidualMode.TAILORED);

            [dxStatePost, ~, ~, ~, dResidual] = SR_UKF_Adaptive_ObsUp(strProblem.dxState, ...
                                                                       strProblem.dStateSqrtCov, ...
                                                                       strProblem.dStateTimetag, ...
                                                                       strProblem.dxSigmaPoints, ...
                                                                       strProblem.strMeasBus, ...
                                                                       strProblem.strDynParams, ...
                                                                       strProblem.strMeasModelParams, ...
                                                                       strProblem.strFilterMutabConfig, ...
                                                                       strProblem.strFilterConstConfig);

            testCase.verifyEqual(dResidual, [0.2; -0.2], 'AbsTol', 1e-9);
            testCase.verifyGreaterThan(dxStatePost(1), strProblem.dxState(1));
            testCase.verifyLessThan(dxStatePost(2), strProblem.dxState(2));
        end

        function testMeasurementEditingCanRejectUpdate(testCase)
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0], ...
                                                               0.1 * eye(2), ...
                                                               [10.0; 10.0], ...
                                                               uint16([1; 2]), ...
                                                               bEnableEditing=true, ...
                                                               dMahaDist2MeasThr=1.0, ...
                                                               ui32MaxNumMeasEditing=uint32(1), ...
                                                               dMeasNoiseVariance=0.01);

            [dxStatePost, ~, ~, strFilterMutabConfig] = SR_UKF_Adaptive_ObsUp(strProblem.dxState, ...
                                                                               strProblem.dStateSqrtCov, ...
                                                                               strProblem.dStateTimetag, ...
                                                                               strProblem.dxSigmaPoints, ...
                                                                               strProblem.strMeasBus, ...
                                                                               strProblem.strDynParams, ...
                                                                               strProblem.strMeasModelParams, ...
                                                                               strProblem.strFilterMutabConfig, ...
                                                                               strProblem.strFilterConstConfig);

            testCase.verifyEqual(dxStatePost, strProblem.dxState, 'AbsTol', 1e-12);
            testCase.verifyEqual(strFilterMutabConfig.ui32MeasEditingCounter, uint32(1));
        end

        function testConsiderStatesModeFreezesSelectedState(testCase)
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0; 3.0], ...
                                                               diag([0.4, 0.4, 0.2]), ...
                                                               [1.2; 1.8], ...
                                                               uint16([1; 2]), ...
                                                               bConsiderStatesMode=logical([false; true; false]));

            [dxStatePost, dStateSqrtCovPost, ~, ~, ~, ~, dxErrState] = SR_UKF_Adaptive_ObsUp(strProblem.dxState, ...
                                                                                               strProblem.dStateSqrtCov, ...
                                                                                               strProblem.dStateTimetag, ...
                                                                                               strProblem.dxSigmaPoints, ...
                                                                                               strProblem.strMeasBus, ...
                                                                                               strProblem.strDynParams, ...
                                                                                               strProblem.strMeasModelParams, ...
                                                                                               strProblem.strFilterMutabConfig, ...
                                                                                               strProblem.strFilterConstConfig);

            dStateCovPost = dStateSqrtCovPost' * dStateSqrtCovPost;
            testCase.verifyEqual(dxErrState(2), 0.0, 'AbsTol', 1e-12);
            testCase.verifyEqual(dxStatePost(2), strProblem.dxState(2), 'AbsTol', 1e-12);
            testCase.verifyEqual(dStateCovPost(2, 2), strProblem.dStateCov(2, 2), 'AbsTol', 1e-12);
        end

        function testAdaptivityUpdatesNoiseFactors(testCase)
            dProcessNoiseCov = 0.05 * eye(6);
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0; 3.0; 4.0; 5.0; 6.0], ...
                                                               diag([0.4, 0.4, 0.2, 0.3, 0.3, 0.3]), ...
                                                               [1.5; 1.2], ...
                                                               uint16([1; 2]), ...
                                                               bEnableAdaptivity=true, ...
                                                               bAdaptMeasNoiseCov=true, ...
                                                               bAdaptProcessNoiseCov=true, ...
                                                               dAdaptiveNoiseAlpha=0.6, ...
                                                               dMeasNoiseVariance=0.02, ...
                                                               dProcessNoiseCov=dProcessNoiseCov);

            dInitialSqrtR = strProblem.strFilterMutabConfig.dsqrtRmeasNoiseCov;
            dInitialSqrtQ = strProblem.strFilterMutabConfig.dsqrtQprocessNoiseCov;

            [~, ~, ~, strFilterMutabConfig] = SR_UKF_Adaptive_ObsUp(strProblem.dxState, ...
                                                                     strProblem.dStateSqrtCov, ...
                                                                     strProblem.dStateTimetag, ...
                                                                     strProblem.dxSigmaPoints, ...
                                                                     strProblem.strMeasBus, ...
                                                                     strProblem.strDynParams, ...
                                                                     strProblem.strMeasModelParams, ...
                                                                     strProblem.strFilterMutabConfig, ...
                                                                     strProblem.strFilterConstConfig);

            testCase.verifyTrue(istriu(strFilterMutabConfig.dsqrtRmeasNoiseCov));
            testCase.verifyTrue(istriu(strFilterMutabConfig.dsqrtQprocessNoiseCov));
            testCase.verifyGreaterThan(norm(strFilterMutabConfig.dsqrtRmeasNoiseCov - dInitialSqrtR, 'fro'), 1e-12);
            testCase.verifyGreaterThan(norm(strFilterMutabConfig.dsqrtQprocessNoiseCov - dInitialSqrtQ, 'fro'), 1e-12);
        end

        function testLatencyMismatchRaisesExplicitError(testCase)
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0; 3.0], ...
                                                               diag([0.4, 0.4, 0.2]), ...
                                                               [1.2; 1.8], ...
                                                               uint16([1; 2]), ...
                                                               dMeasTimetags=[0.5; 0.5]);

            testCase.verifyError(@() SR_UKF_Adaptive_ObsUp(strProblem.dxState, ...
                                                           strProblem.dStateSqrtCov, ...
                                                           strProblem.dStateTimetag, ...
                                                           strProblem.dxSigmaPoints, ...
                                                           strProblem.strMeasBus, ...
                                                           strProblem.strDynParams, ...
                                                           strProblem.strMeasModelParams, ...
                                                           strProblem.strFilterMutabConfig, ...
                                                           strProblem.strFilterConstConfig), ...
                                 'SR_UKF_Adaptive_ObsUp:UnsupportedLatency');
        end
    end
end
