classdef testSR_UKF_TimeUp < matlab.unittest.TestCase
    methods (TestClassSetup)
        function addProjectPaths(~)
            SetupPaths_EstimationGears;

            charThisDir = fileparts(mfilename('fullpath'));
            charHelpersDir = fullfile(charThisDir, '..', 'test_helpers', 'helpers_mocks');
            addpath(genpath(charHelpersDir), '-begin');
        end
    end

    methods (Test)
        function testZeroDeltaReturnsConsistentSigmaPoints(testCase)
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0; 3.0], ...
                                                               diag([0.4, 0.3, 0.2]), ...
                                                               [1.0; 2.0], ...
                                                               uint16([1; 2]));

            [dxStatePrior, dSqrtPrior, dStateTimetag, ~, dxSigmaPointsPrior] = ...
                SR_UKF_TimeUp(strProblem.dxState, ...
                              strProblem.dStateSqrtCov, ...
                              strProblem.dStateTimetag, ...
                              strProblem.dStateTimetag, ...
                              strProblem.strDynParams, ...
                              strProblem.strFilterMutabConfig, ...
                              strProblem.strFilterConstConfig);

            testCase.verifyEqual(dxStatePrior, strProblem.dxState, 'AbsTol', 1e-12);
            testCase.verifyEqual(dSqrtPrior, strProblem.dStateSqrtCov, 'AbsTol', 1e-12);
            testCase.verifyEqual(dStateTimetag, strProblem.dStateTimetag, 'AbsTol', 1e-12);
            testCase.verifyEqual(dxSigmaPointsPrior, strProblem.dxSigmaPoints, 'AbsTol', 1e-12);
        end

        function testMockPropagationShiftsMeanAndPreservesCovariance(testCase)
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0; 3.0], ...
                                                               diag([0.4, 0.3, 0.2]), ...
                                                               [1.0; 2.0], ...
                                                               uint16([1; 2]));

            dTargetTimetag = 0.5;
            [dxStatePrior, dSqrtPrior, dStateTimetag, ~, dxSigmaPointsPrior, ~, ~, ~, ~, dProcessNoiseCov] = ...
                SR_UKF_TimeUp(strProblem.dxState, ...
                              strProblem.dStateSqrtCov, ...
                              strProblem.dStateTimetag, ...
                              dTargetTimetag, ...
                              strProblem.strDynParams, ...
                              strProblem.strFilterMutabConfig, ...
                              strProblem.strFilterConstConfig);

            dStateCovPrior = dSqrtPrior' * dSqrtPrior;
            dSigmaMean = dxSigmaPointsPrior * strProblem.strFilterMutabConfig.dUnscentedWeightsMean;

            testCase.verifyEqual(dxStatePrior, strProblem.dxState + dTargetTimetag, 'AbsTol', 1e-8);
            testCase.verifyEqual(dSigmaMean, dxStatePrior, 'AbsTol', 1e-8);
            testCase.verifyEqual(dStateCovPrior, strProblem.dStateCov, 'AbsTol', 1e-8);
            testCase.verifyEqual(dStateTimetag, dTargetTimetag, 'AbsTol', 1e-12);
            testCase.verifyEqual(dProcessNoiseCov, zeros(3), 'AbsTol', 1e-12);
        end

        function testPiecewiseFlagIsIgnoredAndConsiderStateMode(testCase)
            strProblem = BuildSigmaPointObservationTestProblem([1.0; 2.0; 3.0], ...
                                                               diag([0.4, 0.3, 0.2]), ...
                                                               [1.0; 2.0], ...
                                                               uint16([1; 2]), ...
                                                               bConsiderStatesMode=logical([false; true; false]));

            strFilterMutabConfig = strProblem.strFilterMutabConfig;
            strFilterMutabConfig.bEnablePieceWisePropagation = true;
            strFilterMutabConfig.dMaxPiecewiseTimestep = 0.25;

            [dxStatePrior, dSqrtPrior, dStateTimetag] = ...
                SR_UKF_TimeUp(strProblem.dxState, ...
                              strProblem.dStateSqrtCov, ...
                              strProblem.dStateTimetag, ...
                              1.0, ...
                              strProblem.strDynParams, ...
                              strFilterMutabConfig, ...
                              strProblem.strFilterConstConfig);

            dStateCovPrior = dSqrtPrior' * dSqrtPrior;

            testCase.verifyEqual(dxStatePrior([1; 3]), strProblem.dxState([1; 3]) + 1.0, 'AbsTol', 1e-8);
            testCase.verifyEqual(dxStatePrior(2), strProblem.dxState(2), 'AbsTol', 1e-12);
            testCase.verifyEqual(dStateCovPrior(2, 2), strProblem.dStateCov(2, 2), 'AbsTol', 1e-8);
            testCase.verifyEqual(dStateTimetag, 1.0, 'AbsTol', 1e-12);
        end
    end
end
