% DEPRECATED:
% This legacy test depends on external .mat workspace fixtures.
% Rework it to generated/builder test data before re-enabling it.

close all
clear
clc

error('Deprecated, requires rework.')
% TEST SETUP
%%% DESCRIPTION
% Test script to validate implementation of dynamics jacobians in MSCKF prototype.
% -------------------------------------------------------------------------------------------------------------
%%% CHANGELOG
% 06-03-2025    Pietro Califano     Added tests.
% -------------------------------------------------------------------------------------------------------------
%%% DEPENDENCIES
% dFiniteDiffJac = ComputeFiniteDiffJacobian(fcn_handle, dX0diff, dEps, varargs);

% Load test data from WS file
load('testTimeUpdateWorkspace_SSTO12_t0_after1Update.mat')
dEps = 1e-8;

%% test_DynMatrix
% TODO: test data are to produce again BEFORE the time update call! 
[dxStatePrior, ...
  dxStateCovPrior, ...
  dStateTimetag,...
  dflowSTM,...
  dDynMatrix,...
  dDynMatrixNext, ...
  strFilterMutabConfig] = MSCKF_FullCov_TimeUp(dxState, ...
                                         dxStateCov, ...
                                         dStateTimetag, ...
                                         dTargetTimetag, ...
                                         strDynParams, ...
                                         strFilterMutabConfig, ...
                                         strFilterConstConfig);

dDynMatrix_t0  = computeDynMatrix(dxState, ...
                                0, ...
                                strDynParams, ...
                                strFilterMutabConfig, ...
                                strFilterConstConfig);

fcn_handle_dPosVelState = @(dxPosVel) MSCKF_FullCov_TimeUp([dxPosVel; dxState(7:end)], ...
                                                             dxStateCov, ...
                                                             0, ...
                                                             dTargetTimetag, ...
                                                             strDynParams, ...
                                                             strFilterMutabConfig, ...
                                                             strFilterConstConfig); %#ok<*UNRCH>

dX0diff = dxState(1:6);

% Evaluate STM using FDM
dSTM_PosVel_FDM2ndOrder = ComputeFiniteDiffJacobian(fcn_handle_dPosVelState, dX0diff, dEps, 1, 7);
dSTM_PosVel_FDM2ndOrder = dSTM_PosVel_FDM2ndOrder(1:6,1:6);

dErrorSTM = dSTM_PosVel_FDM2ndOrder(1:6, 1:6) - dflowSTM(1:6,1:6);
assert( all( abs( dErrorSTM ) < 1e-2, 'all'))


% Evaluate JAC using FDM
% For position and velocity RHS ONLY
fcn_handle_DPosVelDt = @(dxStateRV) filterDynOrbit(0, ...
                                                 [dxStateRV; dxState(7:end)], ...
                                                 strDynParams, ...
                                                 strFilterConstConfig);

dJAC_PosVel_FDM2ndOrder = ComputeFiniteDiffJacobian(fcn_handle_DPosVelDt, dX0diff, 1e-9, 1, 1);
dJAC_PosVel_FDM2ndOrder = dJAC_PosVel_FDM2ndOrder(1:6,1:6);

dDynMatrix_rv_t0 = dDynMatrix_t0(1:6,1:6);

dErrorJAC = dJAC_PosVel_FDM2ndOrder(1:6, 1:6) - dDynMatrix_rv_t0;
assert( all(abs(dErrorJAC) < 1e-8, 'all'))





return
